### PR TITLE
patch[openai]: use proxy inheritance for AzureChatOpenAI

### LINKED ISSUE #8544: AzureChatOpenAI doesn't use the provided configs from the constructor
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use the LangChain Forum (https://forum.langchain.com/).
- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The config reads from the env files but if something is not provided it sets default values.
```typescript
const model = new AzureChatOpenAI({
        apiKey: config.azure.apiKey,
        azureOpenAIApiDeploymentName: "gpt-4o",
        azureOpenAIApiInstanceName: config.azure.instanceName,
        azureOpenAIApiVersion: config.azure.openai.apiVersion,
        cache: true,
        model: "gpt-4o",
        temperature: config.openAi.temperature,
});
await model.invoke("Hi");
```

### Error Message and Stack Trace (if applicable)

```
Missing credentials. Please pass one of `apiKey` and `azureADTokenProvider`, or set the `AZURE_OPENAI_API_KEY` environment variable.
Error: Missing credentials. Please pass one of `apiKey` and `azureADTokenProvider`, or set the `AZURE_OPENAI_API_KEY` environment variable.
    at new AzureOpenAI (.../node_modules/openai/src/azure.ts:82:13)
    at ChatOpenAICompletions._getClientOptions (.../node_modules/@langchain/openai/dist/azure/chat_models.cjs:570:27)
    at ChatOpenAICompletions.completionWithRetry (.../node_modules/@langchain/openai/dist/chat_models.cjs:1916:36)
    at ChatOpenAICompletions._streamResponseChunks (.../node_modules/@langchain/openai/dist/chat_models.cjs:1827:43)
    at _streamResponseChunks.next (<anonymous>)
    at AzureChatOpenAI._streamResponseChunks (.../node_modules/@langchain/openai/dist/chat_models.cjs:2678:33)
    at _streamResponseChunks.next (<anonymous>)
    at AzureChatOpenAI._streamIterator (.../node_modules/@langchain/core/dist/language_models/chat_models.cjs:127:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AzureChatOpenAI.transform (.../node_modules/@langchain/core/dist/runnables/base.cjs:410:9)
```

### Description

It appears that AzureChatOpenAI doesn't respect what we're setting in the constructor parameters, but instead just tries to read from the env files directly (which doesn't have everything set because of the default values).

### System Info

Node 24
MacOS

@langchain/openai@0.6.2 | MIT | deps: 3 | versions: 110
OpenAI integrations for LangChain.js
https://github.com/langchain-ai/langchainjs/tree/main/libs/langchain-openai/
keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dependencies (3):
- js-tiktoken: ^1.0.12
- openai: ^5.3.0
- zod: ^3.25.32

dist
 .tarball: https://registry.npmjs.org/@langchain/openai/-/openai-0.6.2.tgz
 .shasum: fb68fa7305ef419e772a56c29146810c0923513d
 .integrity: sha512-OjdSfGENdz4tR9TPN4KTat7vJIE6cgt7vT0z69qU1J1aHCs9MyNwqdaQFF++LVlZAae9aTpyCyqeODyge42oKw==
 .unpackedSize: 0.44 MB

dist-tags:
next: 0.5.3-dev.0
latest: 0.6.2

maintainers:
- hwchase17 <hw.chase.17@gmail.com>
- jacoblee93 <jacoblee93@gmail.com>
- basproul <braceasproul@gmail.com>
- eric_langchain <eric@langchain.dev>
- andrewnguonly <andrewnguonly@gmail.com>
- nfcampos <nuno@boringbits.io>
- davidduong <david@duong.cz>
- maddyadams <madelyn.adams1@gmail.com>
- sam_noyes <sam@langchain.dev>
- hntrl <hunter@hntrl.io>

Published: 2025-07-17T16:36:26.471Z

### LINKED ISSUE #8547: Upgrade to @langchain/openai 0.6.2 breaks AzureChatOpenAI (missing OPENAI_API_VERSION)
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use the LangChain Forum (https://forum.langchain.com/).
- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

No need to put in valid values, the error happens before invoking the final call.

```typescript
await new AzureChatOpenAI({
  model: 'modelName',
  azureOpenAIBasePath: 'azureOpenAIBasePath',
  azureOpenAIApiDeploymentName: 'azureOpenAIApiDeploymentName',
  azureOpenAIApiVersion: 'azureOpenAIApiVersion',
  azureADTokenProvider: () => {
    return Promise.resolve('token');
  },
}).invoke([]);
```

### Error Message and Stack Trace (if applicable)

Error: The OPENAI_API_VERSION environment variable is missing or empty; either provide it, or instantiate the AzureOpenAI client with an apiVersion option, like new AzureOpenAI({ apiVersion: 'My API Version' }).
    at new AzureOpenAI (foo/node_modules/openai/src/azure.ts:72:13)
    at ChatOpenAICompletions._getClientOptions (file://foo/node_modules/@langchain/openai/dist/azure/chat_models.js:567:27)
    at ChatOpenAICompletions.completionWithRetry (file://foo/node_modules/@langchain/openai/dist/chat_models.js:1910:36)
    at ChatOpenAICompletions._generate (file://foo/node_modules/@langchain/openai/dist/chat_models.js:1737:37)
    at AzureChatOpenAI._generate (file://foo/node_modules/@langchain/openai/dist/chat_models.js:2664:33)
    at file://foo/node_modules/@langchain/core/dist/language_models/chat_models.js:250:96
    at Array.map (<anonymous>)
    at AzureChatOpenAI._generateUncached (file://foo/node_modules/@langchain/core/dist/language_models/chat_models.js:250:67)
    at async AzureChatOpenAI.invoke (file://foo/node_modules/@langchain/core/dist/language_models/chat_models.js:88:24)

### Description

Follow up of #8519. After updating to "@langchain/openai": "0.6.2" the error changed from missing api key to missing api version.

### System Info

"@langchain/core": "0.3.66",
"@langchain/textsplitters": "0.1.0",
"langchain": "0.3.30",

### PR DESCRIPTION
**Pull request by hntrl**
Fixes #8547 & fixes #8544

With `@langchain/openai@0.6.0`, we released a substantial refactor of `ChatOpenAI` to give better clarity to the inheritance structure. However, there were some details that got missed specifically with the implementation of `AzureChatOpenAI` (which depends on the new amended inheritance structure), which led to cases where constructor options wouldn't make it all the way through to the inner azure client.

This was allowed to go to a release because we (1) had integration tests that were giving false positives and (2) we didn't really have any testing of azure client options specifically (tests covered initializing from environment vars instead). This addresses both of those issues for future iterations.

This introduces a change that reworks the inheritance structure of `AzureChatOpenAI` so that we can better thread azure specific options to the resulting client object.

**Before**
Screenshot 2025-07-22 at 3 46 18 PM

**After**
Screenshot 2025-07-23 at 2 56 30 PM

### CODE REVIEW

File: libs/langchain-openai/src/azure/chat_models.ts [hunk 1]
```diff
@@ -542,189 +814,20 @@ export class AzureChatOpenAI extends ChatOpenAI {
...
 
-      if (!params.baseURL) {
-        delete params.baseURL;
-      }
-
-      let env = getEnv();
-      if (env === "node" || env === "deno") {
-        env = `(${env}/${process.version}; ${process.platform}; ${process.arch})`;
-      }
+  protected declare completions: AzureChatOpenAICompletions;
```
Comment (jacoblee93) [inline libs/langchain-openai/src/azure/chat_models.ts]: Are these `declare` statements necessary?

File: libs/langchain-openai/src/azure/chat_models.ts [hunk 2]
```diff
@@ -1,27 +1,359 @@
...
+    requestOptions.query = {
+      "api-version": this.azureOpenAIApiVersion,
+      ...requestOptions.query,
+    };
+  }
+  return requestOptions;
+}
+
+function _serializeAzureChat(
+  this: BaseChatOpenAI<ChatOpenAICallOptions> & Partial<AzureOpenAIChatInput>,
```
Comment (jacoblee93) [inline libs/langchain-openai/src/azure/chat_models.ts:162]: nit: A little weird to me to have a param named `this`

File: libs/langchain-openai/src/azure/chat_models.ts (hunk 1 above)
Comment (hntrl) [reply libs/langchain-openai/src/azure/chat_models.ts]: Typescript was complaining without them

File: libs/langchain-openai/src/chat_models.ts [hunk 3]
```diff
@@ -2741,6 +2747,113 @@ export interface ChatOpenAIFields extends BaseChatOpenAIFields {
...
+  /** The responses chat instance */
+  responses: ChatOpenAIResponses;
+  /**
+   * Whether to use the responses API for all requests. If `false` the responses API will be used
+   * only when required in order to fulfill the request.
+   */
+  useResponsesApi?: boolean;
+}
+
+export abstract class ProxyChatOpenAI<
```
Comment (jacoblee93) [inline libs/langchain-openai/src/chat_models.ts]: Why can't this logic live in `BaseChatOpenAI`? A docstring explaining this purpose would be nice

Is the idea to just move `protected declare responses: ChatOpenAIResponses;` down a level?

Alternatively why can't `ChatAzureOpenAI` just inherit from `ChatOpenAI`?

File: libs/langchain-openai/src/azure/chat_models.ts (hunk 2 above)
Comment (hntrl) [reply libs/langchain-openai/src/azure/chat_models.ts:162]: Neat trick of ts: when you define `this` as a param it's strictly for type checking. When js code gets transpiled the only positional argument here ends up being `input`

https://www.typescriptlang.org/docs/handbook/2/functions.html#declaring-this-in-a-function

File: libs/langchain-openai/src/azure/chat_models.ts (hunk 1 above)
Comment (hntrl) [reply libs/langchain-openai/src/azure/chat_models.ts]: Doing some more digging -- it's purely to override the type signature of completions/responses on AzureChatOpenAI. Since there really is no point of having type safety for those members (there's no direct extensions of AzureChatOpenAI that use azure only members), I'm just going to remove it :thumbsup:

File: libs/langchain-openai/src/chat_models.ts (hunk 3 above)
Comment (hntrl) [reply libs/langchain-openai/src/chat_models.ts]: Semantically it's different in my head --

`BaseChatOpenAI` serves as the logical intersection when dealing with an openai chat model. Completions, responses, and ChatOpenAI are all distinctive & valid langchain chat model objects because they inherit from this class.
`ChatOpenAI` selectively routes to completions + responses API based on params. For all intents and purposes though it can be treated as a single chat model (which matches the existing implementation).

File: libs/langchain-openai/src/azure/chat_models.ts (hunk 2 above)
Comment (jacoblee93) [reply libs/langchain-openai/src/azure/chat_models.ts:162]: Cool

File: libs/langchain-openai/src/azure/chat_models.ts [hunk 4]
```diff
@@ -1,27 +1,359 @@
...
+    ) {
+      delete json.kwargs.azure_openai_api_instance_name;
+    }
+  }
+
+  return json;
+}
+
+interface AzureChatOpenAIFields
+  extends BaseChatOpenAIFields,
```
Comment (jacoblee93) [inline libs/langchain-openai/src/azure/chat_models.ts:221]: Should this extend `ChatOpenAIFields` instead?

Comment (hntrl) [reply libs/langchain-openai/src/azure/chat_models.ts:221]: would technically let you supply completions + responses objects by itself which I don't think is desired (ChatOpenAIFields only adds the `useResponsesApi` param which we readd here)

**Comment by hntrl** [comment]
@jacoblee93 

### `ChatOpenAI`
`@0.5.18` trace: https://smith.langchain.com/public/317d1f69-b542-4244-aaf9-33f755265131/r 
after trace: https://smith.langchain.com/public/80c3d093-2738-455d-9071-e0e8e1aa6129/r

### `AzureChatOpenAI`
`@0.5.18` trace: https://smith.langchain.com/public/57a1a828-1a8e-4669-b898-e200d4ead2ff/r
after trace: https://smith.langchain.com/public/83d47804-af21-425f-b330-27a7595bfe90/r

**Review by jacoblee93 — APPROVED** [review]

**Comment by hntrl** [comment]
@jacoblee93 

but this time ✨`withStructuredOutput` ✨

### `AzureChatOpenAI`

`@0.5.18` trace: https://smith.langchain.com/public/c53c0acd-af2a-498a-b0ae-66ab482ffadc/r
after trace: https://smith.langchain.com/public/6cb044cd-2d8c-47fa-9b0a-cdc092548dc4/r

### `ChatOpenAI`

`@0.5.18` trace: https://smith.langchain.com/public/eea20f9f-3c46-41c0-95a9-c1c672e4a02f/r
after trace: https://smith.langchain.com/public/f642a010-7b18-41ef-9fd2-c4e7a69f882a/r
