### PR TITLE
ChatVertexAI: add prompt caching usage metadata

### LINKED ISSUE #8319: [ChatVertexAI] Anthropic models doesn't show prompt caching usage metadata
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

``` typescript
const systemMessage = new SystemMessage({
      content: [
        {
          cache_control: { type: 'ephemeral' },
          text: systemPrompt,
          type: 'text',
        },
      ],
    });

    const humanMessage = HumanMessagePromptTemplate.fromTemplate(userPrompt);

    const chatPrompt = ChatPromptTemplate.fromMessages([systemMessage, humanMessage]);

    const res = await chatModel.invoke(formattedPrompt);
    // res.usage_metadata.cache_read_input_tokens is undefined
```

### Error Message and Stack Trace (if applicable)

_No response_

### Description

Using Anthropic models via ChatVertexAI class doesn't show prompt caching usage metadata

### System Info

````
exports: {
    './hub': {
      types: {
        import: './hub.d.ts',
        default: './hub.d.ts',
        require: './hub.d.cts'
      },
      import: './hub.js',
      require: './hub.cjs'
    },
    './load': {
      types: {
        import: './load.d.ts',
        default: './load.d.ts',
        require: './load.d.cts'
      },
      import: './load.js',
      require: './load.cjs'
    },
    './smith': {
      types: {
        import: './smith.d.ts',
        default: './smith.d.ts',
        require: './smith.d.cts'
      },
      import: './smith.js',
      require: './smith.cjs'
    },
    './tools': {
      types: {
        import: './tools.d.ts',
        default: './tools.d.ts',
        require: './tools.d.cts'
      },
      import: './tools.js',
      require: './tools.cjs'
    },
    './agents': {
      types: {
        import: './agents.d.ts',
        default: './agents.d.ts',
        require: './agents.d.cts'
      },
      import: './agents.js',
      require: './agents.cjs'
    },
    './chains': {
      types: {
        import: './chains.d.ts',
        default: './chains.d.ts',
        require: './chains.d.cts'
      },
      import: './chains.js',
      require: './chains.cjs'
    },
    './memory': {
      types: {
        import: './memory.d.ts',
        default: './memory.d.ts',
        require: './memory.d.cts'
      },
      import: './memory.js',
      require: './memory.cjs'
    },
    './sql_db': {
      types: {
        import: './sql_db.d.ts',
        default: './sql_db.d.ts',
        require: './sql_db.d.cts'
      },
      import: './sql_db.js',
      require: './sql_db.cjs'
    },
    './indexes': {
      types: {
        import: './indexes.d.ts',
        default: './indexes.d.ts',
        require: './indexes.d.cts'
      },
      import: './indexes.js',
      require: './indexes.cjs'
    },
    './document': {
      types: {
        import: './document.d.ts',
        default: './document.d.ts',
        require: './document.d.cts'
      },
      import: './document.js',
      require: './document.cjs'
    },
    './hub/node': {
      types: {
        import: './hub/node.d.ts',
        default: './hub/node.d.ts',
        require: './hub/node.d.cts'
      },
      import: './hub/node.js',
      require: './hub/node.cjs'
    },
    './callbacks': {
      types: {
        import: './callbacks.d.ts',
        default: './callbacks.d.ts',
        require: './callbacks.d.cts'
      },
      import: './callbacks.js',
      require: './callbacks.cjs'
    },
    './tools/sql': {
      types: {
        import: './tools/sql.d.ts',
        default: './tools/sql.d.ts',
        require: './tools/sql.d.cts'
      },
      import: './tools/sql.js',
      require: './tools/sql.cjs'
    },
    './util/math': {
      types: {
        import: './util/math.d.ts',
        default: './util/math.d.ts',
        require: './util/math.d.cts'
      },
      import: './util/math.js',
      require: './util/math.cjs'
    },
    './util/time': {
      types: {
        import: './util/time.d.ts',
        default: './util/time.d.ts',
        require: './util/time.d.cts'
      },
      import: './util/time.js',
      require: './util/time.cjs'
    },
    './evaluation': {
      types: {
        import: './evaluation.d.ts',
        default: './evaluation.d.ts',
        require: './evaluation.d.cts'
      },
      import: './evaluation.js',
      require: './evaluation.cjs'
    },
    './agents/load': {
      types: {
        import: './agents/load.d.ts',
        default: './agents/load.d.ts',
        require: './agents/load.d.cts'
      },
      import: './agents/load.js',
      require: './agents/load.cjs'
    },
    './chains/load': {
      types: {
        import: './chains/load.d.ts',
        default: './chains/load.d.ts',
        require: './chains/load.d.cts'
      },
      import: './chains/load.js',
      require: './chains/load.cjs'
    },
    './tools/chain': {
      types: {
        import: './tools/chain.d.ts',
        default: './tools/chain.d.ts',
        require: './tools/chain.d.cts'
      },
      import: './tools/chain.js',
      require: './tools/chain.cjs'
    },
    './package.json': './package.json',
    './tools/render': {
      types: {
        import: './tools/render.d.ts',
        default: './tools/render.d.ts',
        require: './tools/render.d.cts'
      },
      import: './tools/render.js',
      require: './tools/render.cjs'
    },
    './chains/sql_db': {
      types: {
        import: './chains/sql_db.d.ts',
        default: './chains/sql_db.d.ts',
        require: './chains/sql_db.d.cts'
      },
      import: './chains/sql_db.js',
      require: './chains/sql_db.cjs'
    },
    './text_splitter': {
      types: {
        import: './text_splitter.d.ts',
        default: './text_splitter.d.ts',
        require: './text_splitter.d.cts'
      },
      import: './text_splitter.js',
      require: './text_splitter.cjs'
    },
    './util/document': {
      types: {
        import: './util/document.d.ts',
        default: './util/document.d.ts',
        require: './util/document.d.cts'
      },
      import: './util/document.js',
      require: './util/document.cjs'
    },
    './output_parsers': {
      types: {
        import: './output_parsers.d.ts',
        default: './output_parsers.d.ts',
        require: './output_parsers.d.cts'
      },
      import: './output_parsers.js',
      require: './output_parsers.cjs'
    },
    './agents/toolkits': {
      types: {
        import: './agents/toolkits.d.ts',
        default: './agents/toolkits.d.ts',
        require: './agents/toolkits.d.cts'
      },
      import: './agents/toolkits.js',
      require: './agents/toolkits.cjs'
    },
    './embeddings/fake': {
      types: {
        import: './embeddings/fake.d.ts',
        default: './embeddings/fake.d.ts',
        require: './embeddings/fake.d.cts'
      },
      import: './embeddings/fake.js',
      require: './embeddings/fake.cjs'
    },
    './retrievers/hyde': {
      types: {
        import: './retrievers/hyde.d.ts',
        default: './retrievers/hyde.d.ts',
        require: './retrievers/hyde.d.cts'
      },
      import: './retrievers/hyde.js',
      require: './retrievers/hyde.cjs'
    },
    './stores/doc/base': {
      types: {
        import: './stores/doc/base.d.ts',
        default: './stores/doc/base.d.ts',
        require: './stores/doc/base.d.cts'
      },
      import: './stores/doc/base.js',
      require: './stores/doc/base.cjs'
    },
    './tools/retriever': {
      types: {
        import: './tools/retriever.d.ts',
        default: './tools/retriever.d.ts',
        require: './tools/retriever.d.cts'
      },
      import: './tools/retriever.js',
      require: './tools/retriever.cjs'
    },
    './chains/retrieval': {
      types: {
        import: './chains/retrieval.d.ts',
        default: './chains/retrieval.d.ts',
        require: './chains/retrieval.d.cts'
      },
      import: './chains/retrieval.js',
      require: './chains/retrieval.cjs'
    },
    './runnables/remote': {
      types: {
        import: './runnables/remote.d.ts',
        default: './runnables/remote.d.ts',
        require: './runnables/remote.d.cts'
      },
      import: './runnables/remote.js',
      require: './runnables/remote.cjs'
    },
    './stores/file/node': {
      types: {
        import: './stores/file/node.d.ts',
        default: './stores/file/node.d.ts',
        require: './stores/file/node.d.cts'
      },
      import: './stores/file/node.js',
      require: './stores/file/node.cjs'
    },
    './tools/webbrowser': {
      types: {
        import: './tools/webbrowser.d.ts',
        default: './tools/webbrowser.d.ts',
        require: './tools/webbrowser.d.cts'
      },
      import: './tools/webbrowser.js',
      require: './tools/webbrowser.cjs'
    },
    './cache/file_system': {
      types: {
        import: './cache/file_system.d.ts',
        default: './cache/file_system.d.ts',
        require: './cache/file_system.d.cts'
      },
      import: './cache/file_system.js',
      require: './cache/file_system.cjs'
    },
    './load/serializable': {
      types: {
        import: './load/serializable.d.ts',
        default: './load/serializable.d.ts',
        require: './load/serializable.d.cts'
      },
      import: './load/serializable.js',
      require: './load/serializable.cjs'
    },
    './storage/in_memory': {
      types: {
        import: './storage/in_memory.d.ts',
        default: './storage/in_memory.d.ts',
        require: './storage/in_memory.d.cts'
      },
      import: './storage/in_memory.js',
      require: './storage/in_memory.cjs'
    },
    './memory/chat_memory': {
      types: {
        import: './memory/chat_memory.d.ts',
        default: './memory/chat_memory.d.ts',
        require: './memory/chat_memory.d.cts'
      },
      import: './memory/chat_memory.js',
      require: './memory/chat_memory.cjs'
    },
    './agents/toolkits/sql': {
      types: {
        import: './agents/toolkits/sql.d.ts',
        default: './agents/toolkits/sql.d.ts',
        require: './agents/toolkits/sql.d.cts'
      },
      import: './agents/toolkits/sql.js',
      require: './agents/toolkits/sql.cjs'
    },
    './retrievers/ensemble': {
      types: {
        import: './retrievers/ensemble.d.ts',
        default: './retrievers/ensemble.d.ts',
        require: './retrievers/ensemble.d.cts'
      },
      import: './retrievers/ensemble.js',
      require: './retrievers/ensemble.cjs'
    },
    './storage/file_system': {
      types: {
        import: './storage/file_system.d.ts',
        default: './storage/file_system.d.ts',
        require: './storage/file_system.d.cts'
      },
      import: './storage/file_system.js',
      require: './storage/file_system.cjs'
    },
    './vectorstores/memory': {
      types: {
        import: './vectorstores/memory.d.ts',
        default: './vectorstores/memory.d.ts',
        require: './vectorstores/memory.d.cts'
      },
      import: './vectorstores/memory.js',
      require: './vectorstores/memory.cjs'
    },
    './experimental/autogpt': {
      types: {
        import: './experimental/autogpt.d.ts',
        default: './experimental/autogpt.d.ts',
        require: './experimental/autogpt.d.cts'
      },
      import: './experimental/autogpt.js',
      require: './experimental/autogpt.cjs'
    },
    './experimental/babyagi': {
      types: {
        import: './experimental/babyagi.d.ts',
        default: './experimental/babyagi.d.ts',
        require: './experimental/babyagi.d.cts'
      },
      import: './experimental/babyagi.js',
      require: './experimental/babyagi.cjs'
    },
    './experimental/masking': {
      types: {
        import: './experimental/masking.d.ts',
        default: './experimental/masking.d.ts',
        require: './experimental/masking.d.cts'
      },
      import: './experimental/masking.js',
      require: './experimental/masking.cjs'
    },
    './stores/doc/in_memory': {
      types: {
        import: './stores/doc/in_memory.d.ts',
        default: './stores/doc/in_memory.d.ts',
        require: './stores/doc/in_memory.d.cts'
      },
      import: './stores/doc/in_memory.js',
      require: './stores/doc/in_memory.cjs'
    },
    './chat_models/universal': {
      types: {
        import: './chat_models/universal.d.ts',
        default: './chat_models/universal.d.ts',
        require: './chat_models/universal.d.cts'
      },
      import: './chat_models/universal.js',
      require: './chat_models/universal.cjs'
    },
    './document_loaders/base': {
      types: {
        import: './document_loaders/base.d.ts',
        default: './document_loaders/base.d.ts',
        require: './document_loaders/base.d.cts'
      },
      import: './document_loaders/base.js',
      require: './document_loaders/base.cjs'
    },
    './retrievers/self_query': {
      types: {
        import: './retrievers/self_query.d.ts',
        default: './retrievers/self_query.d.ts',
        require: './retrievers/self_query.d.cts'
      },
      import: './retrievers/self_query.js',
      require: './retrievers/self_query.cjs'
    },
    './stores/file/in_memory': {
      types: {
        import: './stores/file/in_memory.d.ts',
        default: './stores/file/in_memory.d.ts',
        require: './stores/file/in_memory.d.cts'
      },
      import: './stores/file/in_memory.js',
      require: './stores/file/in_memory.cjs'
    },
    './chains/graph_qa/cypher': {
      types: {
        import: './chains/graph_qa/cypher.d.ts',
        default: './chains/graph_qa/cypher.d.ts',
        require: './chains/graph_qa/cypher.d.cts'
      },
      import: './chains/graph_qa/cypher.js',
      require: './chains/graph_qa/cypher.cjs'
    },
    './retrievers/multi_query': {
      types: {
        import: './retrievers/multi_query.d.ts',
        default: './retrievers/multi_query.d.ts',
        require: './retrievers/multi_query.d.cts'
      },
      import: './retrievers/multi_query.js',
      require: './retrievers/multi_query.cjs'
    },
    './schema/prompt_template': {
      types: {
        import: './schema/prompt_template.d.ts',
        default: './schema/prompt_template.d.ts',
        require: './schema/prompt_template.d.cts'
      },
      import: './schema/prompt_template.js',
      require: './schema/prompt_template.cjs'
    },
    './storage/encoder_backed': {
      types: {
        import: './storage/encoder_backed.d.ts',
        default: './storage/encoder_backed.d.ts',
        require: './storage/encoder_backed.d.cts'
      },
      import: './storage/encoder_backed.js',
      require: './storage/encoder_backed.cjs'
    },
    './chains/openai_functions': {
      types: {
        import: './chains/openai_functions.d.ts',
        default: './chains/openai_functions.d.ts',
        require: './chains/openai_functions.d.cts'
      },
      import: './chains/openai_functions.js',
      require: './chains/openai_functions.cjs'
    },
    './embeddings/cache_backed': {
      types: {
        import: './embeddings/cache_backed.d.ts',
        default: './embeddings/cache_backed.d.ts',
        require: './embeddings/cache_backed.d.cts'
      },
      import: './embeddings/cache_backed.js',
      require: './embeddings/cache_backed.cjs'
    },
    './retrievers/multi_vector': {
      types: {
        import: './retrievers/multi_vector.d.ts',
        default: './retrievers/multi_vector.d.ts',
        require: './retrievers/multi_vector.d.cts'
      },
      import: './retrievers/multi_vector.js',
      require: './retrievers/multi_vector.cjs'
    },
    './agents/format_scratchpad': {
      types: {
        import: './agents/format_scratchpad.d.ts',
        default: './agents/format_scratchpad.d.ts',
        require: './agents/format_scratchpad.d.cts'
      },
      import: './agents/format_scratchpad.js',
      require: './agents/format_scratchpad.cjs'
    },
    './agents/xml/output_parser': {
      types: {
        import: './agents/xml/output_parser.d.ts',
        default: './agents/xml/output_parser.d.ts',
        require: './agents/xml/output_parser.d.cts'
      },
      import: './agents/xml/output_parser.js',
      require: './agents/xml/output_parser.cjs'
    },
    './chains/combine_documents': {
      types: {
        import: './chains/combine_documents.d.ts',
        default: './chains/combine_documents.d.ts',
        require: './chains/combine_documents.d.cts'
      },
      import: './chains/combine_documents.js',
      require: './chains/combine_documents.cjs'
    },
    './chains/query_constructor': {
      types: {
        import: './chains/query_constructor.d.ts',
        default: './chains/query_constructor.d.ts',
        require: './chains/query_constructor.d.cts'
      },
      import: './chains/query_constructor.js',
      require: './chains/query_constructor.cjs'
    },
    './document_loaders/fs/json': {
      types: {
        import: './document_loaders/fs/json.d.ts',
        default: './document_loaders/fs/json.d.ts',
        require: './document_loaders/fs/json.d.cts'
      },
      import: './document_loaders/fs/json.js',
      require: './document_loaders/fs/json.cjs'
    },
    './document_loaders/fs/text': {
      types: {
        import: './document_loaders/fs/text.d.ts',
        default: './document_loaders/fs/text.d.ts',
        require: './document_loaders/fs/text.d.cts'
      },
      import: './document_loaders/fs/text.js',
      require: './document_loaders/fs/text.cjs'
    },
    './retrievers/time_weighted': {
      types: {
        import: './retrievers/time_weighted.d.ts',
        default: './retrievers/time_weighted.d.ts',
        require: './retrievers/time_weighted.d.cts'
      },
      import: './retrievers/time_weighted.js',
      require: './retrievers/time_weighted.cjs'
    },
    './schema/query_constructor': {
      types: {
        import: './schema/query_constructor.d.ts',
        default: './schema/query_constructor.d.ts',
        require: './schema/query_constructor.d.cts'
      },
      import: './schema/query_constructor.js',
      require: './schema/query_constructor.cjs'
    },
    './stores/message/in_memory': {
      types: {
        import: './stores/message/in_memory.d.ts',
        default: './stores/message/in_memory.d.ts',
        require: './stores/message/in_memory.d.cts'
      },
      import: './stores/message/in_memory.js',
      require: './stores/message/in_memory.cjs'
    },
    './experimental/openai_files': {
      types: {
        import: './experimental/openai_files.d.ts',
        default: './experimental/openai_files.d.ts',
        require: './experimental/openai_files.d.cts'
      },
      import: './experimental/openai_files.js',
      require: './experimental/openai_files.cjs'
    },
    './output_parsers/expression': {
      types: {
        import: './output_parsers/expression.d.ts',
        default: './output_parsers/expression.d.ts',
        require: './output_parsers/expression.d.cts'
      },
      import: './output_parsers/expression.js',
      require: './output_parsers/expression.cjs'
    },
    './agents/react/output_parser': {
      types: {
        import: './agents/react/output_parser.d.ts',
        default: './agents/react/output_parser.d.ts',
        require: './agents/react/output_parser.d.cts'
      },
      import: './agents/react/output_parser.js',
      require: './agents/react/output_parser.cjs'
    },
    './document_loaders/fs/buffer': {
      types: {
        import: './document_loaders/fs/buffer.d.ts',
        default: './document_loaders/fs/buffer.d.ts',
        require: './document_loaders/fs/buffer.d.cts'
      },
      import: './document_loaders/fs/buffer.js',
      require: './document_loaders/fs/buffer.cjs'
    },
    './retrievers/parent_document': {
      types: {
        import: './retrievers/parent_document.d.ts',
        default: './retrievers/parent_document.d.ts',
        require: './retrievers/parent_document.d.cts'
      },
      import: './retrievers/parent_document.js',
      require: './retrievers/parent_document.cjs'
    },
    './retrievers/score_threshold': {
      types: {
        import: './retrievers/score_threshold.d.ts',
        default: './retrievers/score_threshold.d.ts',
        require: './retrievers/score_threshold.d.cts'
      },
      import: './retrievers/score_threshold.js',
      require: './retrievers/score_threshold.cjs'
    },
    './agents/openai/output_parser': {
      types: {
        import: './agents/openai/output_parser.d.ts',
        default: './agents/openai/output_parser.d.ts',
        require: './agents/openai/output_parser.d.cts'
      },
      import: './agents/openai/output_parser.js',
      require: './agents/openai/output_parser.cjs'
    },
    './chains/query_constructor/ir': {
      types: {
        import: './chains/query_constructor/ir.d.ts',
        default: './chains/query_constructor/ir.d.ts',
        require: './chains/query_constructor/ir.d.cts'
      },
      import: './chains/query_constructor/ir.js',
      require: './chains/query_constructor/ir.cjs'
    },
    './agents/format_scratchpad/log': {
      types: {
        import: './agents/format_scratchpad/log.d.ts',
        default: './agents/format_scratchpad/log.d.ts',
        require: './agents/format_scratchpad/log.d.cts'
      },
      import: './agents/format_scratchpad/log.js',
      require: './agents/format_scratchpad/log.cjs'
    },
    './agents/format_scratchpad/xml': {
      types: {
        import: './agents/format_scratchpad/xml.d.ts',
        default: './agents/format_scratchpad/xml.d.ts',
        require: './agents/format_scratchpad/xml.d.cts'
      },
      import: './agents/format_scratchpad/xml.js',
      require: './agents/format_scratchpad/xml.cjs'
    },
    './document_loaders/fs/directory': {
      types: {
        import: './document_loaders/fs/directory.d.ts',
        default: './document_loaders/fs/directory.d.ts',
        require: './document_loaders/fs/directory.d.cts'
      },
      import: './document_loaders/fs/directory.js',
      require: './document_loaders/fs/directory.cjs'
    },
    './experimental/openai_assistant': {
      types: {
        import: './experimental/openai_assistant.d.ts',
        default: './experimental/openai_assistant.d.ts',
        require: './experimental/openai_assistant.d.cts'
      },
      import: './experimental/openai_assistant.js',
      require: './experimental/openai_assistant.cjs'
    },
    './experimental/plan_and_execute': {
      types: {
        import: './experimental/plan_and_execute.d.ts',
        default: './experimental/plan_and_execute.d.ts',
        require: './experimental/plan_and_execute.d.cts'
      },
      import: './experimental/plan_and_execute.js',
      require: './experimental/plan_and_execute.cjs'
    },
    './chains/history_aware_retriever': {
      types: {
        import: './chains/history_aware_retriever.d.ts',
        default: './chains/history_aware_retriever.d.ts',
        require: './chains/history_aware_retriever.d.cts'
      },
      import: './chains/history_aware_retriever.js',
      require: './chains/history_aware_retriever.cjs'
    },
    './document_loaders/fs/multi_file': {
      types: {
        import: './document_loaders/fs/multi_file.d.ts',
        default: './document_loaders/fs/multi_file.d.ts',
        require: './document_loaders/fs/multi_file.d.cts'
      },
      import: './document_loaders/fs/multi_file.js',
      require: './document_loaders/fs/multi_file.cjs'
    },
    './experimental/generative_agents': {
      types: {
        import: './experimental/generative_agents.d.ts',
        default: './experimental/generative_agents.d.ts',
        require: './experimental/generative_agents.d.cts'
      },
      import: './experimental/generative_agents.js',
      require: './experimental/generative_agents.cjs'
    },
    './chains/combine_documents/reduce': {
      types: {
        import: './chains/combine_documents/reduce.d.ts',
        default: './chains/combine_documents/reduce.d.ts',
        require: './chains/combine_documents/reduce.d.cts'
      },
      import: './chains/combine_documents/reduce.js',
      require: './chains/combine_documents/reduce.cjs'
    },
    './experimental/prompts/handlebars': {
      types: {
        import: './experimental/prompts/handlebars.d.ts',
        default: './experimental/prompts/handlebars.d.ts',
        require: './experimental/prompts/handlebars.d.cts'
      },
      import: './experimental/prompts/handlebars.js',
      require: './experimental/prompts/handlebars.cjs'
    },
    './retrievers/document_compressors': {
      types: {
        import: './retrievers/document_compressors.d.ts',
        default: './retrievers/document_compressors.d.ts',
        require: './retrievers/document_compressors.d.cts'
      },
      import: './retrievers/document_compressors.js',
      require: './retrievers/document_compressors.cjs'
    },
    './retrievers/matryoshka_retriever': {
      types: {
        import: './retrievers/matryoshka_retriever.d.ts',
        default: './retrievers/matryoshka_retriever.d.ts',
        require: './retrievers/matryoshka_retriever.d.cts'
      },
      import: './retrievers/matryoshka_retriever.js',
      require: './retrievers/matryoshka_retriever.cjs'
    },
    './retrievers/self_query/functional': {
      types: {
        import: './retrievers/self_query/functional.d.ts',
        default: './retrievers/self_query/functional.d.ts',
        require: './retrievers/self_query/functional.d.cts'
      },
      import: './retrievers/self_query/functional.js',
      require: './retrievers/self_query/functional.cjs'
    },
    './retrievers/contextual_compression': {
      types: {
        import: './retrievers/contextual_compression.d.ts',
        default: './retrievers/contextual_compression.d.ts',
        require: './retrievers/contextual_compression.d.cts'
      },
      import: './retrievers/contextual_compression.js',
      require: './retrievers/contextual_compression.cjs'
    },
    './experimental/prompts/custom_format': {
      types: {
        import: './experimental/prompts/custom_format.d.ts',
        default: './experimental/prompts/custom_format.d.ts',
        require: './experimental/prompts/custom_format.d.cts'
      },
      import: './experimental/prompts/custom_format.js',
      require: './experimental/prompts/custom_format.cjs'
    },
    './agents/format_scratchpad/openai_tools': {
      types: {
        import: './agents/format_scratchpad/openai_tools.d.ts',
        default: './agents/format_scratchpad/openai_tools.d.ts',
        require: './agents/format_scratchpad/openai_tools.d.cts'
      },
      import: './agents/format_scratchpad/openai_tools.js',
      require: './agents/format_scratchpad/openai_tools.cjs'
    },
    './document_transformers/openai_functions': {
      types: {
        import: './document_transformers/openai_functions.d.ts',
        default: './document_transformers/openai_functions.d.ts',
        require: './document_transformers/openai_functions.d.cts'
      },
      import: './document_transformers/openai_functions.js',
      require: './document_transformers/openai_functions.cjs'
    },
    './agents/format_scratchpad/log_to_message': {
      types: {
        import: './agents/format_scratchpad/log_to_message.d.ts',
        default: './agents/format_scratchpad/log_to_message.d.ts',
        require: './agents/format_scratchpad/log_to_message.d.cts'
      },
      import: './agents/format_scratchpad/log_to_message.js',
      require: './agents/format_scratchpad/log_to_message.cjs'
    },
    './experimental/chains/violation_of_expectations': {
      types: {
        import: './experimental/chains/violation_of_expectations.d.ts',
        default: './experimental/chains/violation_of_expectations.d.ts',
        require: './experimental/chains/violation_of_expectations.d.cts'
      },
      import: './experimental/chains/violation_of_expectations.js',
      require: './experimental/chains/violation_of_expectations.cjs'
    },
    './retrievers/document_compressors/chain_extract': {
      types: {
        import: './retrievers/document_compressors/chain_extract.d.ts',
        default: './retrievers/document_compressors/chain_extract.d.ts',
        require: './retrievers/document_compressors/chain_extract.d.cts'
      },
      import: './retrievers/document_compressors/chain_extract.js',
      require: './retrievers/document_compressors/chain_extract.cjs'
    },
    './retrievers/document_compressors/embeddings_filter': {
      types: {
        import: './retrievers/document_compressors/embeddings_filter.d.ts',
        default: './retrievers/document_compressors/embeddings_filter.d.ts',
        require: './retrievers/document_compressors/embeddings_filter.d.cts'
      },
      import: './retrievers/document_compressors/embeddings_filter.js',
      require: './retrievers/document_compressors/embeddings_filter.cjs'
    }
  },
  gitHead: '2e7279b53c8d245e95f593f2bb44a56f3494c3f0',
  scripts: {
    lint: 'yarn lint:eslint && yarn lint:dpdm',
    test: 'NODE_OPTIONS=--experimental-vm-modules jest --testPathIgnorePatterns=\\.int\\.test.ts --testTimeout 30000 --maxWorkers=50%',
    build: 'yarn turbo:command build:internal --filter=langchain',
    clean: 'rm -rf .turbo dist/',
    format: 'prettier --config .prettierrc --write "src"',
    prepack: 'yarn build',
    release: 'release-it --only-version --config .release-it.json',
    'lint:fix': 'yarn lint:eslint --fix && yarn lint:dpdm',
    'lint:dpdm': 'dpdm --exit-code circular:1 --no-warning --no-tree src/*.ts src/**/*.ts',
    precommit: 'lint-staged',
    'test:watch': 'NODE_OPTIONS=--experimental-vm-modules jest --watch --testPathIgnorePatterns=\\.int\\.test.ts',
    'lint:eslint': 'NODE_OPTIONS=--max-old-space-size=4096 eslint --cache --ext .ts,.js src/',
    'test:single': 'NODE_OPTIONS=--experimental-vm-modules yarn run jest --config jest.config.cjs --testTimeout 100000',
    'format:check': 'prettier --config .prettierrc --check "src"',
    'build:internal': 'yarn lc_build --create-entrypoints --pre --tree-shaking --gen-maps',
    'test:integration': 'NODE_OPTIONS=--experimental-vm-modules jest --testPathPattern=\\.int\\.test.ts --testTimeout 100000 --maxWorkers=50%'
  },
  directories: {},
  dependencies: {
    zod: '^3.22.4',
    uuid: '^10.0.0',
    yaml: '^2.2.1',
    'js-yaml': '^4.1.0',
    'p-retry': '4',
    langsmith: '^0.3.29',
    'js-tiktoken': '^1.0.12',
    jsonpointer: '^5.0.1',
    'openapi-types': '^12.1.3',
    '@langchain/openai': '>=0.1.0 <0.6.0',
    'zod-to-json-schema': '^3.22.3',
    '@langchain/textsplitters': '>=0.0.0 <0.2.0'
  },
  publishConfig: {
    access: 'public'
  },
  devDependencies: {
    dpdm: '^3.12.0',
    jest: '^29.5.0',
    axios: '^0.26.0',
    peggy: '^3.0.2',
    dotenv: '^16.0.3',
    eslint: '^8.33.0',
    openai: '^4.41.1',
    rimraf: '^5.0.1',
    rollup: '^3.19.1',
    cheerio: '1.0.0-rc.12',
    'ts-jest': '^29.1.0',
    typeorm: '^0.3.20',
    prettier: '^2.8.3',
    '@swc/core': '^1.3.90',
    '@swc/jest': '^0.2.29',
    '@types/ws': '^8',
    wikipedia: '^2.1.2',
    handlebars: '^4.7.8',
    'release-it': '^18.1.2',
    typescript: '~5.1.6',
    '@types/uuid': '^9',
    '@types/jsdom': '^21.1.1',
    '@jest/globals': '^29.5.0',
    '@langchain/aws': '*',
    '@langchain/xai': '*',
    '@types/js-yaml': '^4',
    '@faker-js/faker': '^7.6.0',
    '@langchain/core': 'workspace:*',
    '@langchain/groq': '*',
    'reflect-metadata': '^0.2.2',
    '@langchain/cohere': '*',
    '@langchain/ollama': '*',
    '@types/handlebars': '^4.1.0',
    '@langchain/scripts': '>=0.1.0 <0.2.0',
    'eslint-plugin-jest': '^27.6.0',
    '@langchain/cerebras': '*',
    '@langchain/deepseek': '*',
    '@types/html-to-text': '^9',
    '@langchain/anthropic': '*',
    '@langchain/mistralai': '*',
    'eslint-plugin-import': '^2.27.5',
    '@tsconfig/recommended': '^1.0.2',
    'jest-environment-node': '^29.6.4',
    'eslint-config-prettier': '^8.6.0',
    'eslint-plugin-prettier': '^4.2.1',
    '@langchain/google-genai': '*',
    '@typescript-eslint/parser': '^5.58.0',
    'eslint-config-airbnb-base': '^15.0.0',
    '@langchain/google-vertexai': '*',
    'eslint-plugin-no-instanceof': '^1.0.1',
    '@langchain/google-vertexai-web': '*',
    '@typescript-eslint/eslint-plugin': '^5.58.0'
  },
  peerDependencies: {
    axios: '*',
    peggy: '^3.0.2',
    cheerio: '*',
    typeorm: '*',
    handlebars: '^4.7.8',
    '@langchain/aws': '*',
    '@langchain/xai': '*',
    '@langchain/core': '>=0.2.21 <0.4.0',
    '@langchain/groq': '*',
    '@langchain/cohere': '*',
    '@langchain/ollama': '*',
    '@langchain/cerebras': '*',
    '@langchain/deepseek': '*',
    '@langchain/anthropic': '*',
    '@langchain/mistralai': '*',
    '@langchain/google-genai': '*',
    '@langchain/google-vertexai': '*',
    '@langchain/google-vertexai-web': '*'
  },
  peerDependenciesMeta: {
    axios: {
      optional: true
    },
    peggy: {
      optional: true
    },
    cheerio: {
      optional: true
    },
    typeorm: {
      optional: true
    },
    handlebars: {
      optional: true
    },
    '@langchain/aws': {
      optional: true
    },
    '@langchain/xai': {
      optional: true
    },
    '@langchain/groq': {
      optional: true
    },
    '@langchain/cohere': {
      optional: true
    },
    '@langchain/ollama': {
      optional: true
    },
    '@langchain/cerebras': {
      optional: true
    },
    '@langchain/deepseek': {
      optional: true
    },
    '@langchain/anthropic': {
      optional: true
    },
    '@langchain/mistralai': {
      optional: true
    },
    '@langchain/google-genai': {
      optional: true
    },
    '@langchain/google-vertexai': {
      optional: true
    },
    '@langchain/google-vertexai-web': {
      optional: true
    }
  }
}
````

### PR DESCRIPTION
**Pull request by keremnalbant**
Add mapping for `cache_read_input_tokens` and `cache_creation_input_tokens` for `ChatVertexAI` class.

Fixes #8319

### CODE REVIEW

**Comment by keremnalbant** [comment]
A pretty quick win to monitor usage metadata for prompt caching.

cc @jacoblee93

File: libs/langchain-google-common/src/utils/anthropic.ts [hunk 1]
```diff
@@ -211,6 +211,8 @@ export function getAnthropicAPI(config?: AnthropicAPIConfig): GoogleAIAPI {
       input_tokens: usage?.input_tokens ?? 0,
       output_tokens: usage?.output_tokens ?? 0,
       total_tokens: (usage?.input_tokens ?? 0) + (usage?.output_tokens ?? 0),
+      cache_read_input_tokens: usage?.cache_read_input_tokens ?? 0,
+      cache_creation_input_tokens: usage?.cache_creation_input_tokens ?? 0,
```
Comment (afirstenberg) [inline libs/langchain-google-common/src/utils/anthropic.ts]: I think that the `usageMetadata` object should be changed to meet the definitions of `UsageMetadata`, which I think was added since this function was created.

As such, the `cache_read` and `cache_creation` values should be set in the `usageMetadata.input_token_details` object.

This would have the Vertex+Anthropic support use the same standard the rest of LangChainJS is using.

Comment (keremnalbant) [reply libs/langchain-google-common/src/utils/anthropic.ts]: That makes sense tho, thanks for the heads up @afirstenberg! Updated the PR.

**Comment by afirstenberg** [comment]
#lgtm

**Comment by hntrl** [comment]
@keremnalbant thank you!
