### PR TITLE
fix(langchain): Prevent local file corruption when using `LocalFileStore` 

### LINKED ISSUE #9337: Concurrent `LocalFileStore` `mset` writes can corrupt chunked embeddings cache
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use the LangChain Forum (https://forum.langchain.com/).
- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Reproducable Example

```typescript

import { LocalFileStore } from "@langchain/classic/storage/file_system";

const run = async () => {
  const store = await LocalFileStore.fromPath("./cache");
  const encoder = new TextEncoder();

  const PARALLEL_CALLS = 100;
  const CHUNKS_PER_CALL = 10;
  const MIN_BYTES = 5;
  const MAX_BYTES = 50;

  // helper to make a large string payload
  const makePayload = (id: number) => {
    const size = Math.floor(Math.random() * (MAX_BYTES - MIN_BYTES + 1)) + MIN_BYTES;
    const chunk = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    let s = "";
    while (Buffer.byteLength(s, "utf8") < size) {
      s += chunk[Math.floor(Math.random() * chunk.length)];
    }

    if (Buffer.byteLength(s, "utf8") > size) {
      while (Buffer.byteLength(s, "utf8") > size) s = s.slice(0, -1);
    }
    const base = { chunkId: id, data: s };
    return JSON.stringify(base);
  };

  const promises: Promise<void>[] = [];
  for (let i = 0; i < PARALLEL_CALLS; i++) {
    const callIndex = i;
    promises.push(
      (async () => {
        const entries: [string, Uint8Array][] = [];
        for (let j = 0; j < CHUNKS_PER_CALL; j++) {
          const payload = makePayload(callIndex * CHUNKS_PER_CALL + j);
          entries.push(["message", encoder.encode(payload)]);
        }
        await store.mset(entries);
      })()
    );
  }

  await Promise.all(promises);
  await store.mget(["message"]);
};

run()
```

Produces `message.txt` with the following data.

```json
{"chunkId":998,"data":"0vCRvGfwpgqwixqYFQgo59xUn"}rY"}04Fsfa6N"}5"}Ys"}"}"}
```

### Error Message and Stack Trace (if applicable)

_No response_

### Description

* I am using `CharacterTextSplitter` and `CacheBackedEmbeddings` with `LocalFileStore`
* I expected to have locally cached embeddings that could be re-used.
* Instead there were JSON serialization errors while reading from the cache.

### System Info

```bash
langchain@1.0.3 | MIT | deps: 5 | versions: 343
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-1.0.3.tgz
.shasum: d2ca5e0bf1882678d556b087783b373f92d86677
.integrity: sha512-nGxI9li1yttHzLHtECgw3hGMNzEDQR+EpW4kHKy1mbWjyBXtUDI6SyHjAeOAX7c6oV1QYRlFsOlXtahPiMySpQ==
.unpackedSize: 4.2 MB

dependencies:
@langchain/langgraph-checkpoint: ^1.0.0 langsmith: ~0.3.74                      zod: ^3.25.76 || ^4
@langchain/langgraph: ^1.0.0            uuid: ^10.0.0

maintainers:
- christian-bromann <mail@bromann.dev>
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- andrewnguonly <andrewnguonly@gmail.com>
- davidduong <david@duong.cz>
- hntrl <hunter@hntrl.io>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
alpha: 1.0.0-alpha.9                       next: 1.0.0-alpha.9
latest: 1.0.3                              tag-for-publishing-older-releases: 0.2.20

published 19 hours ago by christian-bromann <mail@bromann.dev>
```

`platform` Linux - Ubuntu - 6.6.87.2-microsoft-standard-WSL2

`node --version` - v24.6.0

`pnpm --version` 10.20.0

### PR DESCRIPTION
**Pull request by Josh-Engle**
# Description

This PR addresses a race condition in `LocalFileStore` where concurrent writes to the same key could lead to data loss or corruption. Previously, multiple `mset` operations on the same key would execute in parallel, causing file writes to overwrite each other. Additionally, added guards against incomplete file writes due to unexpected process termination.

This is addressed through a number of mechanisms.
- Dedupe keys within the same `mset` call to ensure the last one is written.
- Use a promise queue to guarantee sequential execution across multiple `mset` calls.
- Write to tmp files and then rename to text files prevent partial writes in the case of unexpected termination.

Fixes #9337

### CODE REVIEW

File: libs/langchain-classic/src/storage/file_system.ts [hunk 1]
```diff
@@ -194,6 +221,82 @@ export class LocalFileStore extends BaseStore<string, Uint8Array> {
...
+          await fs.unlink(tempPath).catch(() => {});
+        } else {
+          throw renameError;
+        }
+      }
+    } catch (error) {
+      await fs.unlink(tempPath).catch(() => {});
+      throw error;
+    }
+  }
```
Comment (hntrl) [inline libs/langchain-classic/src/storage/file_system.ts:301]: What's the purpose of the temp files if we're sequencing files using `withKeyLock`?

**Review by hntrl — COMMENTED** [review]
Thanks @Josh-Engle! One Q about your approach:

File: libs/langchain-classic/src/storage/file_system.ts (hunk 1 above)
Comment (Josh-Engle) [reply libs/langchain-classic/src/storage/file_system.ts:301]: This is an added guard to prevent partial file writes causing data corruption if the process terminates before the buffer is fully flushed for a particular file. 

We write to the temp file first as this might be interrupted. If it is interrupted, only the temp file is corrupted which is cleaned up. Once we have fully flushed the fs buffer and we know it's in a good state, we overwrite the previous file with the `rename` which cannot be interrupted as it is either successful or not.

Comment (hntrl) [reply libs/langchain-classic/src/storage/file_system.ts:301]: Is that a common occurrence? What is the rename operation fails?

Comment (Josh-Engle) [reply libs/langchain-classic/src/storage/file_system.ts:301]: It's hard to say if it's common but I can image relatively likely scenarios and the problem tends to scale up with larger file sizes. Larger files mean larger write times, increasing the chance of a failure mid-write. 

A good example might be:

1. A developer force terminates the process execution while `LocalFileStore` is halfway through writing a file to the file system.
2. The incomplete write operation results in malformed JSON as it is not terminated correctly.
3. Reading the `txt` file results in an invalid JSON exception.

The `rename` operation is considerably more reliable then the `writeFile` because it's a single operation. If we have already written data to the filesystem with `writeFile` it's very likely the `rename` will work correctly as it requires the same OS filesystem permissions. 

For windows I think it would only fail if there was a open file handle and on Linux it would fail if it doesn't have access to the directory. In both cases I think a failure is expected.

Comment (Josh-Engle) [reply libs/langchain-classic/src/storage/file_system.ts:301]: @hntrl Would you prefer I remove the atomic file writes to keep the PR focused?

Comment (hntrl) [reply libs/langchain-classic/src/storage/file_system.ts:301]: Yeah I think that's preferred. Unless we have a concrete case/ MRE that triggers this that we think is reasonable, I want to air on the side of not over optimizing too early
