### PR TITLE
fix(community): Add INSERT support to PrismaVectorStore for ParentDocumentRetriever compatibility (#8833)

### LINKED ISSUE #8833: Can not use ParentDocumentRetriever with Prisma
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use the LangChain Forum (https://forum.langchain.com/).
- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

File: `node_modules\@langchain\community\dist\vectorstores\prisma.cjs`
Function: `addVectors`
Line: 159
Error code:
```
await this.db.$transaction(vectors.map((vector, idx) => this.db.$executeRaw(this.Prisma.sql `UPDATE ${tableNameRaw}
            SET ${vectorColumnRaw} = ${`[${vector.join(",")}]`}::vector
            WHERE ${idColumnRaw} = ${documents[idx].metadata[this.idColumn]}
          `)));
```

### Error Message and Stack Trace (if applicable)

_No response_

### Why it's a bug:
When integrate with `ParentDocumentRetriever` follow this doc: https://js.langchain.com/docs/how_to/parent_document_retriever/
- `ParentDocumentRetriever` create child vector record automatically but prisma use UPDATE statement, it must be create or update
- It doesn't throw any error cause SQL statement is successful but no record is created

### System Info

Node 22
Windows/Mac
"@langchain/community": "^0.3.41",
"@langchain/core": "^0.3.49",

### PR DESCRIPTION
**Pull request by christian-bromann**
Previously, PrismaVectorStore only used UPDATE statements when adding vectors, which caused silent failures when used with ParentDocumentRetriever. The retriever creates new child documents that don't exist in the database, so UPDATE statements would succeed but not create any records.

Changes:
- Add new `addDocumentsWithVectors` method that uses INSERT statements to create records
- Modify `addDocuments` to use `addDocumentsWithVectors` instead of `addVectors`
- Maintain backward compatibility by keeping the original `addVectors` method unchanged
- Add tests to verify the new behavior and ensure no regression

This fix ensures PrismaVectorStore works correctly with ParentDocumentRetriever while maintaining compatibility with existing code.

Fixes #8833

### CODE REVIEW

**Comment by ivaaaan** [comment]
I've faced this issue. Basically, PrismaVectorStore is not usable if you're trying to store multiple chunks per document. Are there plans to merge this?

**Comment by christian-bromann** [comment]
@hntrl is this good to go?

File: libs/langchain-community/src/vectorstores/prisma.ts [hunk 1]
```diff
@@ -286,7 +286,7 @@ export class PrismaVectorStore<
    */
   async addDocuments(documents: Document<TModel>[]) {
     const texts = documents.map(({ pageContent }) => pageContent);
-    return this.addVectors(
+    return this.addDocumentsWithVectors(
       await this.embeddings.embedDocuments(texts),
       documents
```
Comment (hntrl) [inline libs/langchain-community/src/vectorstores/prisma.ts]: I think we want to put this new insert logic behind a flag? Especially when it comes to database interactions I want to avoid changing up write ops haphazardly unless it's in a breaking change, and we don't really have a want to minor bump the community package ATM

Comment (christian-bromann) [reply libs/langchain-community/src/vectorstores/prisma.ts]: @ivaaaan what are your thoughts here, how breaking would this change be?

Comment (ivaaaan) [reply libs/langchain-community/src/vectorstores/prisma.ts]: I guess makes sense. For my case it wouldn't be breaking change as PrismaVectorStore doesn't work with UPDATE, not sure about others.

**Comment by christian-bromann** [comment]
@hntrl put the change behind a flag
