### PR TITLE
fix(core): use input param for schema serialization

### LINKED ISSUE #8367: Zod 4 - toJSONSchema should use the 'input' type
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Just any schema with a transform, e.g something like

```typescript
const getEventTool = tool(
  async ({ eventId }) => {
    throw new Error("Not implemented");
  },
  {
    name: "getEvent",
    description: "Retrieves an event by its ID",
    schema: z.object({
      eventId: z.string().transform(id => DatabaseId.make(id)).describe("The unique identifier for the event"),
    }),
  }
);
```

### Error Message and Stack Trace (if applicable)

```
Error: Transforms cannot be represented in JSON Schema
    at JSONSchemaGenerator.process (file:///[REDACTED]/node_modules/zod/dist/esm/v4/core/to-json-schema.js:401:35)
    at JSONSchemaGenerator.process (file:///[REDACTED]/node_modules/zod/dist/esm/v4/core/to-json-schema.js:464:30)
    at JSONSchemaGenerator.process (file:///[REDACTED]/node_modules/zod/dist/esm/v4/core/to-json-schema.js:52:22)
    at JSONSchemaGenerator.process (file:///[REDACTED]/node_modules/zod/dist/esm/v4/core/to-json-schema.js:188:57)
    at toJSONSchema (file:///[REDACTED]/node_modules/zod/dist/esm/v4/core/to-json-schema.js:727:9)
    at toJsonSchema (file:///[REDACTED]/node_modules/@langchain/core/dist/utils/json_schema.js:13:16)
    at convertToOpenAIFunction (file:///[REDACTED]/node_modules/@langchain/core/dist/utils/function_calling.js:21:21)
    at convertToOpenAITool (file:///[REDACTED]/node_modules/@langchain/core/dist/utils/function_calling.js:44:23)
    at *convertToOpenAITool (file:///[REDACTED]/node*modules/@langchain/openai/dist/utils/tools.js:19:19)
    at *convertChatOpenAIToolTypeToOpenAITool (file:///[REDACTED]/node*modules/@langchain/openai/dist/chat_models.js:666:12) {
  pregelTaskId: '938b08ff-78c3-55bd-b563-e3d230b0980f'
}
```

### Description

I am trying out zod 4 with our tools, and the first thing I ran into is that transform is not supported for the json schema.

I have tools with inputs such as:
```ts
            eventId: z
                .string()
                .transform((id) => DatabaseId.make(id)),
```

Zod 4's json schema implementation does consider transforms [unrepresentable](https://zod.dev/json-schema?id=unrepresentable), which is fair enough if this was the _output_ schema, however this is for tool **input**.

I believe the the tools should be using the `input` schema mode for toJSONSchema, see the docs https://zod.dev/json-schema?id=io

When I patch langchain locally with `{ io: "input" }` to test this theory, it works as expected!

### System Info

  Node.js Version: v22.14.0

  LangChain Versions:
  - @langchain/community@0.3.46
  - @langchain/core@0.3.58
  - @langchain/google-genai@0.2.12
  - @langchain/langgraph-checkpoint@0.0.18
  - @langchain/langgraph@0.3.3
  - @langchain/openai@0.5.13

  Zod Version: 3.25.64

### PR DESCRIPTION
**Pull request by hntrl**
Fixes #8367

### CODE REVIEW

File: langchain-core/src/utils/json_schema.ts [hunk 1]
```diff
@@ -14,7 +21,12 @@ export { deepCompareStrict, Validator } from "@cfworker/json-schema";
  */
 export function toJsonSchema(schema: InteropZodType | JSONSchema): JSONSchema {
   if (isZodSchemaV4(schema)) {
-    return toJSONSchema(schema);
+    if (isZodObjectV4(schema)) {
+      const strictSchema = interopZodObjectStrict(schema, true) as ZodObjectV4;
+      return toJSONSchema(strictSchema, { io: "input" });
+    } else {
+      return toJSONSchema(schema, { io: "input" });
+    }
```
Comment (hntrl) [inline langchain-core/src/utils/json_schema.ts]: Its okay to assume that we should use the input side of the schema entirely here since the zodToJsonSchema utility that's been around for a while defaults to using that.

Zod's json schema serializer also assumes that the input side for object schemas should mean there's no `additionalProperties` output on the JSON schema unless its an explicit strict object. This also departs from zodToJsonSchema's behavior, so `interopZodObjectStrict` recursively applies strict conditions to the object so that this field populates.

Comment (hntrl) [reply langchain-core/src/utils/json_schema.ts]: related: https://github.com/colinhacks/zod/pull/4365

File: langchain-core/src/output_parsers/tests/structured.test.ts [hunk 2]
```diff
@@ -343,7 +343,7 @@ describe("StructuredOutputParser.fromZodSchema", () => {
...
+    {"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"url":{"description":"A link to the resource","type":"string"},"title":{"description":"A title for the resource","type":"string"},"year":{"description":"The year the resource was created","type":"number"},"createdAt":{"description":"The date and time the resource was created","type":"string"},"createdAtDate":{"description":"The date the resource was created","type":"string"},"authors":{"type":"array","items":{"type":"object","properties":{"name":{"description":"The name of the author","type":"string"},"email":{"description":"The email of the author","type":"string"},"type":{"type":"string","enum":["author","editor"]},"address":{"description":"The address of the author","type":"string"},"stateProvince":{"description":"The state or province of the author","type":"string","enum":["AL","AK","AZ"]}},"required":["name","email"],"additionalProperties":false}}},"required":["url","title","year","createdAt","authors"],"additionalProperties":false,"description":"Only One object"}
```
Comment (hntrl) [inline langchain-core/src/output_parsers/tests/structured.test.ts:346]: The zod 4 json schema serializer doesnt have stable key ordering
