### PR TITLE
community[patch]: Update ElasticSearch mappings to successfully add documents from TextSplitter

### LINKED ISSUE #2857: Elastic Search Vector Store - Unable to Add Documents
Unable to add documents to Elastic Search Vector Store.

```typescript
  const loader = new DirectoryLoader("./documents", {
    ".txt": (path) => new TextLoader(path),
  });
  const documents = await loader.load()
  const text_splitter = new CharacterTextSplitter({chunkSize:1000, chunkOverlap:0})
  const docs = await text_splitter.splitDocuments(documents)
  console.log("Docs found...."+docs.length);
  const embeddings = new OpenAIEmbeddings();
  const vectorStore = new ElasticVectorSearch(embeddings, clientArgs);
  const ids = await vectorStore.addDocuments(docs);
 
 // the following statement returns IDs but the insertion fails.
  console.log("Docs loaded...."+ids.length);
``` 

There is no error logged and the `ids` array is non-null, but the underlying vector store has no documents.

[Full Code](https://gist.github.com/vinodkiran/d299f8f0137dc52f6bee5c5782953e84)

### PR DESCRIPTION
**Pull request by mattraibert**
Fixes #2857

Explicitly map `.metadata.loc` as an object in Elasticsearch. `.metadata.*` was mapped to only allow keywords. So Elasticsearch would reject the object inserted at `.metadata.loc` by a `TextSplitter`.

Also throw an error when failing to insert into Elasticsearch.

The same solution could be applied to #1589 and #2036

https://github.com/langchain-ai/langchainjs/blob/2527979ccb1626ab993687810a805147cc24c619/libs/langchain-community/src/vectorstores/opensearch.ts#L254-L279

### CODE REVIEW

File: libs/langchain-community/src/vectorstores/elasticsearch.ts [hunk 1]
```diff
@@ -266,16 +270,23 @@ export class ElasticVectorSearch extends VectorStore {
       mappings: {
         dynamic_templates: [
           {
-            // map all metadata properties to be keyword
-            "metadata.*": {
+            // map all metadata properties to be keyword except loc
+            metadata_except_loc: {
```
Comment (jacoblee93) [inline libs/langchain-community/src/vectorstores/elasticsearch.ts:274]: Is there we can generalize this a bit more to handle all object properties?

Comment (mattraibert) [reply libs/langchain-community/src/vectorstores/elasticsearch.ts:274]: Thanks for reviewing!

One reason I did it this way is that I tried to be as focused as possible on fixing the bug and leaving other existing behavior alone.

We could possibly use object type for every metadata field and perhaps it's the right thing to do given that `metadata` is defined as `Record<string, any>`. I think it would be like this:

```js
            "metadata.*": {
              match_mapping_type: "*",
              match: "metadata.*",
              mapping: { type: "object" },
            },
```

But I think there are a couple of reasonable arguments for keeping `metadata` fields declared as `keyword` in Elasticsearch. Searching through the codebase, I see that `loc` is the only field that is ever anything but a flat number or string. And I think being able to filter by `keyword` type fields is much simpler and more performant in Elasticsearch. For my use case, for example, I want to augment an embedding based search with keyword filtering, so I'd prefer to keep them as keywords.

Another solution to #2857 could be to change the way `loc` is stored so that it can be stored in a keyword field. The `TextSplitter`s could store something like `line_from` and `line_to`. In that case, it might make sense to update the type of `metadata` as well. This might be a bigger lift since it would potentially affect anything downstream of those `TextSplitter`s.

Comment (jacoblee93) [reply libs/langchain-community/src/vectorstores/elasticsearch.ts:274]: Yeah we can't change text splitter metadata yet, though I think flattening it would be nice when we're ready to make a breaking change.

Comment (jacoblee93) [reply libs/langchain-community/src/vectorstores/elasticsearch.ts:274]: I'm ok with this but can we add a TODO in the code as well? Also remember to run `yarn lint`!

**Comment by jacoblee93** [comment]
Thanks!

**Comment by jacoblee93** [comment]
Thank you!
