### PR TITLE
community[patch]: fix: #4997 zhipu chat model response typeError

### LINKED ISSUE #4997: TypeError when invoke ZhipuAI chatmodel with invalid api key
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
import { ChatZhipuAI } from "@langchain/community/chat_models/zhipuai";

const model = new ChatZhipuAI({
     modelName: "glm-4", // Available models:
     temperature: 1,
     zhipuAIApiKey: "invalid api key", 
});
 const res = await model.invoke([new HumanMessage("Hello")]);
```

### Error Message and Stack Trace (if applicable)

        TypeError: Cannot read properties of undefined (reading '0')
                    at /node_modules/@langchain/community/dist/chat_models/zhipuai.cjs:209:64
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)
                    at ChatZhipuAI._generate (/node_modules/@langchain/community/dist/chat_models/zhipuai.cjs:202:15)
                    at async Promise.allSettled (index 0)
                    at ChatZhipuAI._generateUncached (/node_modules/@langchain/core/dist/language_models/chat_models.cjs:118:25)
                    at ChatZhipuAI.invoke (/node_modules/@langchain/core/dist/language_models/chat_models.cjs:54:24)

### Description

I am trying to use `ChatZhipuAI` in my project.
Code is here:
```
import { ChatZhipuAI } from "@langchain/community/chat_models/zhipuai";

const model = new ChatZhipuAI({
     modelName: "glm-4", // Available models:
     temperature: 1,
     zhipuAIApiKey: "invalid api key", 
});
 const res = await model.invoke([new HumanMessage("Hello")]);
```
You will get a TypeError if you run the code.

You can find the error point here: [zhipuai.ts#327](https://github.com/langchain-ai/langchainjs/blob/d6e25af137873493d30bdf5732d46b842e421ffa/libs/langchain-community/src/chat_models/zhipuai.ts#L327) 

The reason is that ZhipuChatModel will return `{error: {code: 1002, message: 'error message'}} ` not `{ code: 1002, message: 'error message' } `when you invoke with invalid api key.

So the error will not be caught by [zhipuai.ts#324](https://github.com/langchain-ai/langchainjs/blob/d6e25af137873493d30bdf5732d46b842e421ffa/libs/langchain-community/src/chat_models/zhipuai.ts#L324), lead to the TypeError.

### System Info

  "langchain": "^0.1.31",
  "@langchain/community": "0.0.44",

### PR DESCRIPTION
**Pull request by jeasonnow**
Fixes #4997

### CODE REVIEW

File: libs/langchain-community/src/chat_models/zhipuai.ts [hunk 1]
```diff
@@ -67,10 +67,14 @@ interface ResponseChoice {
   message: ChoiceMessage;
 }
 
+interface ErrorResponse {
+  error: BaseResponse;
```
Comment (jacoblee93) [inline libs/langchain-community/src/chat_models/zhipuai.ts:71]: Could we call `BaseResponse` something else? How about `ZhipuAIError`?

Comment (jeasonnow) [reply libs/langchain-community/src/chat_models/zhipuai.ts:71]: Yes, we can rename BaseResponse. ZhipuAIError sounds like a good alternative.

**Review by bracesproul — APPROVED** [review]
Lgtm, thanks for doing this!
