### PR TITLE
community[patch]: anthropic add tool call support new tools api

### LINKED ISSUE #5639: langchain-community/chat_models/Bedrock [Feature]: Agent with Tools using Bedrock Anthropic Claude new tools API
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
import { config } from 'dotenv';
import { BedrockChat } from "@langchain/community/chat_models/bedrock";
// import { BedrockChat } from "./custom-models/index"; // this is my upadted version of BedrockChat that I want to propose as a PR
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { z } from "zod";
import { createToolCallingAgent, AgentExecutor } from "langchain/agents";
import { DynamicStructuredTool } from "@langchain/core/tools";

config(); // load .env file

if (!process?.env?.AWSAccessKeyId || !process?.env?.AWSSecretAccessKey) {
    console.error('AWSAccessKeyId or AWSSecretAccessKey not found in .env file');
    process.exit(1);
}

const addTool = new DynamicStructuredTool({
    name: "add",
    description: "Add two integers together.",
    schema: z.object({
        firstInt: z.number(),
        secondInt: z.number(),
    }),
    func: async ({ firstInt, secondInt }) => {
        console.log('------ Function called with: -----------', { firstInt, secondInt });
        return (firstInt + secondInt).toString();
    },
});

async function test() {
    const model = new BedrockChat({
        model: "anthropic.claude-3-sonnet-20240229-v1:0",
        temperature: 0.5,
        region: "us-east-1",
        credentials: {
            accessKeyId: process.env.AWSAccessKeyId as string,
            secretAccessKey: process.env.AWSSecretAccessKey as string,
        },
    });
    
    const prompt = ChatPromptTemplate.fromMessages([
        ["system", "You are a helpful assistant"],
        ["placeholder", "{chat_history}"],
        ["human", "{input}"],
        ["placeholder", "{agent_scratchpad}"],
    ])
    
    const agent = createToolCallingAgent({
        llm: model,
        tools: [addTool],
        prompt: prompt,
        streamRunnable: false // attempt to work around streaming issue with tools
    });
    
    const agentExecutor = new AgentExecutor({ 
        agent,
        tools: [addTool],
        // verbose: true,
        returnIntermediateSteps: true,
    });
    
    const r = await agentExecutor.invoke({ input: "Hi! Can you tell me what is 10 + 4?" });
    console.log(r);
    console.log(r.content);
}

test();
```

### Error Message and Stack Trace (if applicable)

This agent requires that the "bind_tools()" method be implemented on the input model.

### Description

* I'm trying to use LangChain JS to create Tool Calling agent on Amazon Bedrock, using Claude 3 model with latest tools APi
* I get above error because in community/Bedrock this is not implemented yet
* I've finished this implementation on my own (mostly copying from Anthropic implementation) and would like to make a PR with it, and get support to finish it - as I don't have experience contributing to this project
* On my local test the function call gets executed as follows:

```
Binding tools to model [
  DynamicStructuredTool {
    lc_serializable: false,
    lc_kwargs: {
      name: 'add',
      description: 'Add two integers together.',
      schema: [ZodObject],
      func: [AsyncFunction: func]
    },
    lc_runnable: true,
    name: 'add',
    verbose: false,
    callbacks: undefined,
    tags: [],
    metadata: {},
    returnDirect: false,
    description: 'Add two integers together.',
    func: [AsyncFunction: func],
    schema: ZodObject {
      spa: [Function: bound safeParseAsync] AsyncFunction,
      _def: [Object],
      parse: [Function: bound parse],
      safeParse: [Function: bound safeParse],
      parseAsync: [Function: bound parseAsync] AsyncFunction,
      safeParseAsync: [Function: bound safeParseAsync] AsyncFunction,
      refine: [Function: bound refine],
      refinement: [Function: bound refinement],
      superRefine: [Function: bound superRefine],
      optional: [Function: bound optional],
      nullable: [Function: bound nullable],
      nullish: [Function: bound nullish],
      array: [Function: bound array],
      promise: [Function: bound promise],
      or: [Function: bound or],
      and: [Function: bound and],
      transform: [Function: bound transform],
      brand: [Function: bound brand],
      default: [Function: bound default],
      catch: [Function: bound catch],
      describe: [Function: bound describe],
      pipe: [Function: bound pipe],
      readonly: [Function: bound readonly],
      isNullable: [Function: bound isNullable],
      isOptional: [Function: bound isOptional],
      _cached: null,
      nonstrict: [Function: passthrough],
      augment: [Function: extend]
    }
  }
]
------ Function called with: ----------- { firstInt: 10, secondInt: 4 }
{
  input: 'Hi! Can you tell me what is 10 + 4?',
  output: '10 + 4 = 14',
  intermediateSteps: [ { action: [Object], observation: '14' } ]
}
undefined
```

### System Info

npm info langchain:
```
langchain@0.2.4 | MIT | deps: 16 | versions: 276
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-0.2.4.tgz
.shasum: a85295e2510425cc5f4aca32bc9adeda88f6918d
.integrity: sha512-zBsBuNREn/3IlWvIQqhQ2iqf6JJhyjjsB1Db/keDkcgThPI3EcblC1pqAXU2BIKHmpNUkHBR2bAUok5+xtgOcw==
.unpackedSize: 4.0 MB

dependencies:
@langchain/core: ~0.2.0          js-tiktoken: ^1.0.12             langsmith: ~0.1.30               uuid: ^9.0.0
@langchain/openai: ~0.1.0        js-yaml: ^4.1.0                  ml-distance: ^4.0.0              yaml: ^2.2.1
@langchain/textsplitters: ~0.0.0 jsonpointer: ^5.0.1              openapi-types: ^12.1.3           zod-to-json-schema: ^3.22.3
binary-extensions: ^2.2.0        langchainhub: ~0.0.8             p-retry: 4                       zod: ^3.22.4

maintainers:
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- andrewnguonly <andrewnguonly@gmail.com>
- davidduong <david@duong.cz>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
latest: 0.2.4     next: 0.2.3-rc.0

published 3 days ago by jacoblee93 <jacoblee93@gmail.com>
```

Windows 11 64bit
Node v20.14.0
No yarn atm

### PR DESCRIPTION
**Pull request by LordMsz**
This is a proposal to add support for latest tools call API for Anthropic models on Amazon Bedrock in LangChain / Community.
I originally developed my own solution, but then realized it basically matches solution in https://github.com/LordMsz/langchainjs/blob/main/libs/langchain-anthropic/src/chat_models.ts .
So I tried to sync as much as sensible as part of this change.

I'd like to ask for help getting this finalized, as I don't have experience contributing to this repo or LangChain in general.

I tested the code locally running following code:
```typescript
import { config } from 'dotenv';
// import { BedrockChat } from "@langchain/community/chat_models/bedrock";
import { BedrockChat } from "./custom-models/index"; // this is my upadted version of BedrockChat that I want to propose as a PR
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { z } from "zod";
import { createToolCallingAgent, AgentExecutor } from "langchain/agents";
import { DynamicStructuredTool } from "@langchain/core/tools";

config(); // load .env file

if (!process?.env?.AWSAccessKeyId || !process?.env?.AWSSecretAccessKey) {
    console.error('AWSAccessKeyId or AWSSecretAccessKey not found in .env file');
    process.exit(1);
}

const addTool = new DynamicStructuredTool({
    name: "add",
    description: "Add two integers together.",
    schema: z.object({
        firstInt: z.number(),
        secondInt: z.number(),
    }),
    func: async ({ firstInt, secondInt }) => {
        console.log('------ Function called with: -----------', { firstInt, secondInt });
        return (firstInt + secondInt).toString();
    },
});

async function test() {
    const model = new BedrockChat({
        model: "anthropic.claude-3-sonnet-20240229-v1:0",
        temperature: 0.5,
        region: "us-east-1",
        credentials: {
            accessKeyId: process.env.AWSAccessKeyId as string,
            secretAccessKey: process.env.AWSSecretAccessKey as string,
        },
    });
    
    const prompt = ChatPromptTemplate.fromMessages([
        ["system", "You are a helpful assistant"],
        ["placeholder", "{chat_history}"],
        ["human", "{input}"],
        ["placeholder", "{agent_scratchpad}"],
    ])
    
    const agent = createToolCallingAgent({
        llm: model,
        tools: [addTool],
        prompt: prompt,
        streamRunnable: false // attempt to work around streaming issue with tools
    });
    
    const agentExecutor = new AgentExecutor({ 
        agent,
        tools: [addTool],
        // verbose: true,
        returnIntermediateSteps: true,
    });
    
    const r = await agentExecutor.invoke({ input: "Hi! Can you tell me what is 10 + 4?" });
    console.log(r);
    console.log(r.content);
}

test();
```

Fixes #5639 (issue)

### CODE REVIEW

**Comment by jakowenko** [comment]
Thanks for putting this together! Make sure you format and lint the code as a large portion of the diff seems to be related to that.

**Comment by LordMsz** [comment]
Apologies for the linting and formatting issue - fixed now.
I struggle to get the complete build and test of project working for some reason, but I tried all the changes with copy of the models. Any help with proper build highly appreciated!

**Comment by jacoblee93** [comment]
This is massive - thank you so much for this!

Will have a look tomorrow.

**Comment by jacoblee93** [comment]
I wonder if there's a way to reuse some of the existing logic we have in `@langchain/anthropic` - might have a short look to avoid duplication.

**Comment by LordMsz** [comment]
Hi,
sure, I was also thinking that way - was surprised that big chunks of code are almost a copy from `@langchain/anthropic`.
Ideally we would re-use it all and in Bedrock wrapper only authentication would be handled?

What is your suggestion? Should I expose the utilized methods in `@langchain/anthropic`, e.g. _mergeMessages. and import them here, or something else?

**Comment by jacoblee93** [comment]
Yes that's what I was thinking - if you're willing to take it on I think that'd be a good approach!

CC @efriis to weigh in as well.

**Comment by LordMsz** [comment]
Okay, working on it now.
I'm also trying to resolve my local build issue - seems I was missing Python 3.11 (required for node-gyp) and now I need C++ Workload in VS to add "msvs_version".
Is this documented anywhere as a per-requisite for development? Sorry if I missed it.

File: libs/langchain-anthropic/src/index.ts [hunk 1]
```diff
@@ -1 +1,2 @@
 export * from "./chat_models.js";
+export * from "./output_parsers.js";
```
Comment (LordMsz) [inline libs/langchain-anthropic/src/index.ts:2]: This change is biggest question for me - if it's inline with overall "strategy" that I can export this from Anthropic and use it in community? Any thoughts?
I only need single function from there, so that could be a minor copy-paste I assume.

**Comment by jacoblee93** [comment]
Thanks for looking into this! I can resolve the build issue, it should just be dev dependencies I think.

File: libs/langchain-anthropic/src/index.ts (hunk 1 above)
Comment (jacoblee93) [reply libs/langchain-anthropic/src/index.ts:2]: Yeah I think that's fine. Maybe we can prefix it with an underscore to show that it shouldn't be imported directly.

**Comment by LordMsz** [comment]
Perfect! Thanks. Please let me know if anything I could do.

**Comment by michaelozery** [comment]
@LordMsz Thank you very much for this!
Could you please also [update the docs(https://js.langchain.com/v0.2/docs/integrations/chat/)? 
(Give the tool calling cell a yellow circle)

**Comment by LordMsz** [comment]
Sure thing, done. Thanks for reminder!

**Comment by jacoblee93** [comment]
Will need to split the Anthropic changes into a separate PR

**Comment by jacoblee93** [comment]
Am actually backtracking now - dependencies in community have been a bit more problematic lately :(

Will just copy out the relevant code from Anthropic

**Comment by LordMsz** [comment]
Thanks for the help with this! :)

**Comment by jacoblee93** [comment]
Thank you for the awesome start!

Will try to land tonight

**Comment by kamilcglr** [comment]
Hello, thank you all for the quick integration. 

Is it normal for streaming not to work when using the createToolCallingAgent function? I see that [https://github.com/langchain-ai/langchainjs/pull/5640/commits/8f7191536e0cfd606329cd1ffd15fff75390c4df](commit) contains the term streaming, but I don't understand if it's just about calling tools in an async way or all events.

My use case is as follows: I am using the stream function and I want to send all the generations of the final response token by token to my client using websocket using the 'on_llm_stream' event.

**Comment by jacoblee93** [comment]
Hey @kamilcglr, are you talking about `streamEvents`?

Proper streaming tool calls will take a bit more work - the delegation you see in that commit just invokes and yields the non-streaming result from Bedrock as a single chunk. You should still see it as an `on_chat_model_stream` event though.

**Comment by kamilcglr** [comment]
Hello @jacoblee93 

Yes, I am talking about `streamEvents`, but I do not necessarily want to stream the tools, just the final answer. 

Here is an example of what I am trying to do. I have a class with a run function that starts the process and sends event to my frontend application. 
I used to use a similar class in Python with an SQL Agent and Bedrock with Claude 3. I managed to send all the tokens to my frontend one by one (with the on_chat_model_stream event).

```typescript
class AgentService {
  private agent

  constructor() {}

  async initialize() {
    if (this.agent) return

    const llm = new BedrockChat({
      model: 'anthropic.claude-3-sonnet-20240229-v1:0',
      region: 'us-west-2',
      streaming: true,
      temperature: 0,
    })

    const tools = [
      ... some DynamicStructuredTools ...
    ]

    const agent = createToolCallingAgent({
      llm,
      tools,
      prompt: customPrompt,
      streamRunnable: true,
    })

    const agentExecutor = new AgentExecutor({
      agent,
      tools,
      handleParsingErrors: true,
      returnIntermediateSteps: true,
    }).withConfig({ runName: 'llm_agent' })

    const messageHistory = (id: string) =>
      new DynamoDBChatMessageHistory({
        tableName: 'SessionTable',
        partitionKey: 'SessionId',
        sessionId: id,
        config: {
          region: 'us-west-2',
        },
      })

    const runnableWithMessageHistory = new RunnableWithMessageHistory({
      runnable: agentExecutor,
      getMessageHistory: (sessionId: string) => messageHistory(sessionId),
      inputMessagesKey: 'input',
      historyMessagesKey: 'history',
    })

    this.agent = runnableWithMessageHistory
  }

  async run(input: string, sessionId: string) {
    // [This is where an event is sent to the client to say that the process has started]

    const eventStream = await this.agent.stream(
      { input: input },
      {
        configurable: {
          sessionId: sessionId,
        },
        version: 'v1',
      }
    )

    for await (const item of eventStream) {
      if (item.event === 'on_llm_stream') {
        // Here I send "item.data.chunk.content" to the client as a completion
        // But it sends everything in a single event, whereas I expect something like: Hello,| how |can |I |help |you ? where ‘|’ is an event
      }

      if (item.event === 'on_chain_end') {
       // [End event is sent]
      }
    }
  }
}
```

**Comment by Moe03** [comment]
> Hello @jacoblee93
> 
> Yes, I am talking about `streamEvents`, but I do not necessarily want to stream the tools, just the final answer.
> 
> Here is an example of what I am trying to do. I have a class with a run function that starts the process and sends event to my frontend application. I used to use a similar class in Python with an SQL Agent and Bedrock with Claude 3. I managed to send all the tokens to my frontend one by one (with the `on_chat_model_stream` event).
> 
> ```ts
> class AgentService {
>   private agent
> 
>   constructor() {}
> 
>   async initialize() {
>     if (this.agent) return
> 
>     const llm = new BedrockChat({
>       model: 'anthropic.claude-3-sonnet-20240229-v1:0',
>       region: 'us-west-2',
>       streaming: true,
>       temperature: 0,
>     })
> 
>     const tools = [
>       ... some DynamicStructuredTools ...
>     ]
> 
>     const agent = createToolCallingAgent({
>       llm,
>       tools,
>       prompt: customPrompt,
>       streamRunnable: true,
>     })
> 
>     const agentExecutor = new AgentExecutor({
>       agent,
>       tools,
>       handleParsingErrors: true,
>       returnIntermediateSteps: true,
>     }).withConfig({ runName: 'llm_agent' })
> 
>     const messageHistory = (id: string) =>
>       new DynamoDBChatMessageHistory({
>         tableName: 'SessionTable',
>         partitionKey: 'SessionId',
>         sessionId: id,
>         config: {
>           region: 'us-west-2',
>         },
>       })
> 
>     const runnableWithMessageHistory = new RunnableWithMessageHistory({
>       runnable: agentExecutor,
>       getMessageHistory: (sessionId: string) => messageHistory(sessionId),
>       inputMessagesKey: 'input',
>       historyMessagesKey: 'history',
>     })
> 
>     this.agent = runnableWithMessageHistory
>   }
> 
>   async run(input: string, sessionId: string) {
>     // [This is where an event is sent to the client to say that the process has started]
> 
>     const eventStream = await this.agent.streamEvents(
>       { input: input },
>       {
>         configurable: {
>           sessionId: sessionId,
>         },
>         version: 'v1',
>       }
>     )
> 
>     for await (const item of eventStream) {
>       if (item.event === 'on_llm_stream') {
>         // Here I send "item.data.chunk.content" to the client as a completion
>         // But it sends everything in a single event, whereas I expect something like: Hello,| how |can |I |help |you ? where ‘|’ is an event
>       }
> 
>       if (item.event === 'on_chain_end') {
>        // [End event is sent]
>       }
>     }
>   }
> }
> ```

Would love to also stream the events properly since we have a setup for multiple llms, providers and its crucial the stream events is working across all these models, it currently doesn't work for claude-3.5-sonnet

**Comment by jacoblee93** [comment]
Thanks folks, we've implemented and merged in Python already. Will try to get to it this week, stay tuned!
