### PR TITLE
google-common[patch]: Add `method` property to GoogleAISafetySetting interface

### LINKED ISSUE #6309: VertexAI doesn't allow safetySettings param method
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
 new VertexAI({
            model: this.LLM_MODEL,
            verbose: this.verbose,
            temperature: 0,
            authOptions,
            location: this.LOCATION,
            endpoint: `${this.LOCATION}-aiplatform.googleapis.com`,
            safetySettings: [
                {
                    category: 'HARM_CATEGORY_HATE_SPEECH',
                    threshold: 'BLOCK_ONLY_HIGH',
                    method: 'SEVERITY',
                },
                {
                    category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
                    threshold: 'BLOCK_ONLY_HIGH',
                    method: 'SEVERITY',
                },
                {
                    category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
                    threshold: 'BLOCK_ONLY_HIGH',
                    method: 'SEVERITY',
                },
                {
                    category: 'HARM_CATEGORY_HARASSMENT',
                    threshold: 'BLOCK_ONLY_HIGH',
                    method: 'SEVERITY',
                },
            ],
        });
``` 

### Error Message and Stack Trace (if applicable)

Object literal may only specify known properties, and 'method' does not exist in type 'GoogleAISafetySetting'.

### Description

When you want to configure the gemini-pro safetySettings cannot set the setting method to "SEVERITY". That option is very usefull when you want to configure the LLM's safety settings. In interface `GoogleAISafetySettings` only can configurate "category" and "threshold" but in Gemini's documentation has this: 

The Vertex AI Gemini API provides two "harm block" methods:

SEVERITY: This method uses both probability and severity scores.
PROBABILITY: This method uses the probability score only.
The default method is PROBABILITY. To learn more, see [HarmBlockMethod API reference](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.types.SafetySetting.HarmBlockMethod).

The Vertex AI Gemini API provides the following "harm block" thresholds:

BLOCK_LOW_AND_ABOVE: Block when the probability score or the severity score is LOW, MEDIUM or HIGH.
BLOCK_MEDIUM_AND_ABOVE: Block when the probability score or the severity score is MEDIUM or HIGH.
BLOCK_ONLY_HIGH: Block when the probability score or the severity score is HIGH.
HARM_BLOCK_THRESHOLD_UNSPECIFIED: Block using the default threshold.
BLOCK_NONE (Restricted): The BLOCK_NONE safety setting removes automated response blocking and lets you configure your own safety guidelines with the returned scores. This is a restricted field that isn't available to all users in [GA](https://cloud.google.com/products#product-launch-stages) model versions. BLOCK_NONE is not supported for audio and video input when you're using Gemini 1.5 Flash or Gemini 1.5 Pro.

https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/configure-safety-attributes#vertex-ai-gemini-api

### System Info

{
  name: 'langchain',
  'dist-tags': {
    next: '0.2.3-rc.0',
    latest: '0.2.12'
  },
}

### PR DESCRIPTION
**Pull request by marsal**
Fixes #6309

### CODE REVIEW

File: libs/langchain-google-common/src/types.ts [hunk 1]
```diff
@@ -45,6 +45,7 @@ export interface GoogleConnectionParams<AuthOptions>
 export interface GoogleAISafetySetting {
   category: string;
   threshold: string;
+  method: string
```
Comment (bracesproul) [inline libs/langchain-google-common/src/types.ts:48]: Needs to be an optional arg, otherwise anyone populating this field who upgrades will be forced to populate this too.
```suggestion
  method?: string
```

**Review by bracesproul — APPROVED** [review]
One small nit, thanks for adding this!

**Review by bracesproul — APPROVED** [review]
thank you!
