### PR TITLE
fix(google): Using .nullish() in zod.

### LINKED ISSUE #8162: ChatVertexAI Tool Calling With Gemini 2.5 Flash Schema Cannot Contain .nullish()
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
import {
  ChatPromptTemplate,
  MessagesPlaceholder,
} from "@langchain/core/prompts";
import {
  Annotation,
  Command,
  messagesStateReducer,
  StateGraph,
} from "@langchain/langgraph";
import {
  AIMessage,
  BaseMessage,
  SystemMessage,
  HumanMessage,
} from "@langchain/core/messages";
import { ToolNode } from "@langchain/langgraph/prebuilt";
import debug from "debug";
import { tool } from "@langchain/core/tools";
import { nan, z } from "zod";

import { InMemoryStore } from "@langchain/langgraph";
import { nanoid } from "nanoid";
import { ChatVertexAI } from "@langchain/google-vertexai";

export const gemini = new ChatVertexAI({
  model: "gemini-2.5-flash-preview-04-17",
  temperature: 0.2,
  location: "us-central1",
  maxRetries: 2,
});

export const store = new InMemoryStore();

export const getWeather = tool(
  async (input) => {
    return "The weather is 72 degrees and sunny.";
  },
  {
    name: "get_weather",
    description: "Gets the weather for a particular zip code",
    schema: z.object({
      localeData: z.object({
        zipCode: z
          .string()
          .nullish()
          .describe(
            "The zip code of the area for which to retrieve the weather.",
          ),
      }),
    }),
  },
);

const log = debug("lite");

export const State = Annotation.Root({
  messages: Annotation<BaseMessage[]>({
    reducer: messagesStateReducer,
    default: () => [],
  }),
});

// Define the function that determines whether to continue or not
async function shouldContinue({ messages }: typeof State.State, config: any) {
  const lastMessage = messages[messages.length - 1] as AIMessage;

  // If the LLM makes a tool call, then we route to the "tools" node
  if (lastMessage.tool_calls?.length) {
    return "tools";
  }
  return "__end__";
}

const invokeLiteGraph = async (state: typeof State.State) => {
  const configurable = {
    thread_id: nanoid(),
    messageId: nanoid(),
  };
  console.log(configurable);
  const llm = gemini;

  const tools = [getWeather];

  const messages = [
    new SystemMessage(
      "Answer the users request using the tools at your desposal",
    ),
  ] as any[];

  const prompt = ChatPromptTemplate.fromMessages([
    ...messages,
    new MessagesPlaceholder("messages"),
  ]);

  const toolNode = new ToolNode(tools);

  const modelWithTools = llm.bindTools(tools);

  // Define the function that calls the model
  async function callModel(state: typeof State.State) {
    const messages = [...state.messages];

    const chain = prompt.pipe(modelWithTools);

    const response = await chain.invoke(
      {
        ...state,
        messages,
      },
      { maxConcurrency: 50, configurable },
    );
    return {
      messages: [response],
      final_response: response.content,
    };
  }

  // Define a new graph for the lite agent
  const workflow = new StateGraph(State)
    .addNode("agent", callModel)
    .addEdge("__start__", "agent") // __start__ is a special name for the entrypoint
    .addNode("tools", toolNode)
    .addEdge("tools", "agent")
    .addConditionalEdges("agent", shouldContinue);

  const compiledLiteGraph = workflow.compile({ store: store });

  const result = await compiledLiteGraph.invoke(
    {
      messages: state.messages,
    },
    {
      configurable,
      maxConcurrency: 50,
    },
  );

  return result;
};

await invokeLiteGraph({
  messages: [new HumanMessage("Whats the weather in 90210?")],
});
```

### Error Message and Stack Trace (if applicable)

 Invalid JSON payload received. Unknown name "type" at 'tools[0].function_declarations[14].parameters.properties[1].value': Proto field is not repeating, cannot start list.
Invalid JSON payload received. Unknown name "type" at 'tools[0].function_declarations[15].parameters.properties[1].value': Proto field is not repeating, cannot start list.
Invalid JSON payload received. Unknown name "type" at 'tools[0].function_declarations[16].parameters.properties[0].value.items.properties[2].value': Proto field is not repeating, cannot start list.
Invalid JSON payload received. Unknown name "type" at 'tools[0].function_declarations[16].parameters.properties[0].value.items.properties[3].value': Proto field is not repeating, cannot start list.
Invalid JSON payload received. Unknown name "type" at 'tools[0].function_declarations[17].parameters.properties[1].value': Proto field is not repeating, cannot start list.
Invalid JSON payload received. Unknown name "type" at 'tools[0].function_declarations[18].parameters.properties[0].value.items.properties[3].value': Proto field is not repeating, cannot start list.
Invalid JSON payload received. Unknown name "type" at 'tools[0].function_declarations[18].parameters.properties[0].value.items.properties[4].value': Proto field is not repeating, cannot start list.
Invalid JSON payload received. Unknown name "type" at 'tools[0].function_declarations[18].parameters.properties[0].value.items.properties[6].value': Proto field is not repeating, cannot start list.
Invalid JSON payload received. Unknown name "type" at 'tools[0].function_declarations[21].parameters.properties[0].value.items.properties[3].value': Proto field is not repeating, cannot start list.

### Description

Tools that contain .nullish in their schema definitions will cause a 400 bad request error when using ChatVertexAI  with Gemini 2.5 Flash

### System Info

    "@langchain/core": "0.3.55",
    "@langchain/google-vertexai": "^0.2.8",
    "@langchain/langgraph": "^0.2.71",

### PR DESCRIPTION
**Pull request by afirstenberg**
See #8162 for detailed analysis.
Resolved the issue by using the existing `removeAdditionalProperties()` function in zod_to_gemini_parameters.ts to cleanup the `type` property and possibly add the `nullable` property.

Fixes #8162

### CODE REVIEW

File: libs/langchain-google-common/src/utils/zod_to_gemini_parameters.ts [hunk 1]
```diff
@@ -20,6 +20,16 @@ export function removeAdditionalProperties(
       delete newObj.additionalProperties;
     }
 
+    if (Array.isArray(obj.type)) {
+      // Gemini requires type be a string, so we use the first defined one
+      newObj.type = obj?.type[0];
```
Comment (benjamincburns) [inline libs/langchain-google-common/src/utils/zod_to_gemini_parameters.ts:25]: Does this mean that if it's a union we drop the other parts? If yes, perhaps it's better to throw here (except in the case when the union is `[someAllowedType, null]`, maybe?) than silently drop a potentially important part of the schema?

Comment (afirstenberg) [reply libs/langchain-google-common/src/utils/zod_to_gemini_parameters.ts:25]: It pains me to say this - but yeah, probably should throw an exception here in that case.

I don't think I realized that unions would be doing it this way, since the OpenAPI 3 spec doesn't allow for `type` to have multiple values.

Comment (afirstenberg) [reply libs/langchain-google-common/src/utils/zod_to_gemini_parameters.ts]: Update pushed to handle.

**Review by benjamincburns — APPROVED** [review]
