### PR TITLE
fix(cohere,langchain): handle exceptions in compressDocuments and formatDocuments methods due to empty documents

### LINKED ISSUE #7370: Cohere rerank exception: invalid request: list of documents must not be empty
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
const retriever = vectorstore.asRetriever();

const cohereRerank = new CohereRerank({
    apiKey: COHERE_API_KEY,
    model: "rerank-v3.5",
    topN: 3,
});

const contextualCompressionRetriever = new ContextualCompressionRetriever({
    baseCompressor: cohereRerank,
    baseRetriever: retriever,
});

const stream = await ragChain.stream({
    chat_history: chatHistoryParsedArray,
    input: sanitizedText,
});
```

### Error Message and Stack Trace (if applicable)

BadRequestError
Status code: 400
Body: {
  "message": "invalid request: list of documents must not be empty"
}
/node_modules/langchain/dist/chains/combine_documents/base.js:8
    const formattedDocs = await Promise.all(documents.map((document) => documentPrompt
                                                      ^

TypeError: Cannot read properties of undefined (reading 'map')
    at formatDocuments (/node_modules/langchain/dist/chains/combine_documents/base.js:8:55)
    at RunnableLambda.func (/node_modules/langchain/dist/chains/combine_documents/stuff.js:27:90)
    at /node_modules/@langchain/core/dist/runnables/base.js:1735:44
    at MockAsyncLocalStorage.run (/node_modules/@langchain/core/dist/singletons/async_local_storage/index.js:10:16)
    at AsyncLocalStorageProvider.runWithConfig (/node_modules/@langchain/core/dist/singletons/async_local_storage/index.js:53:24)
    at output (/node_modules/@langchain/core/dist/runnables/base.js:1733:53)
    at new Promise (<anonymous>)
    at RunnableLambda._transform (/node_modules/@langchain/core/dist/runnables/base.js:1732:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RunnableLambda._transformStreamWithConfig (/node_modules/@langchain/core/dist/runnables/base.js:301:30)

### Description

I'm using the Cohere reranker, and it throws an exception when the retriever has empty documents. This prevents the AI for generating a response.

The ideal behavior should be to return an empty list so that the AI can generate a response based on the instructions we've given it.

Edit: this issue is similar to the ones reported in the Java and Python versions of Langchain, which were fixed a long time ago:

https://github.com/langchain4j/langchain4j/issues/770
https://github.com/langchain-ai/langchain/issues/5304

### System Info

Package versions:
"langchain": "^0.3.7"
"@langchain/cohere": "^0.3.1"
"@langchain/core": "^0.3.23"

### PR DESCRIPTION
**Pull request by ahm750**
Fixes #7370

1. Prevent the ```invalid request: list of documents must not be empty``` error caused by ```compressDocuments``` method due to ```documents``` being empty. Added a condition to check if ```documents``` is empty. If yes, return an empty array.

2. Prevent exception thrown from ```formattedDocs``` methods when ```documents``` is empty. Added a condition to check if ```documents``` is empty. If yes, return an empty string.

### CODE REVIEW

File: langchain/src/chains/combine_documents/base.ts [hunk 1]
```diff
@@ -21,6 +21,9 @@ export async function formatDocuments({
   documents: Document[];
   config?: RunnableConfig;
 }) {
+  if (documents == null || documents.length == 0) {
```
Comment (jacoblee93) [inline langchain/src/chains/combine_documents/base.ts:24]: Don't think we need the `.length` check

Also should use triple equals if at all

File: libs/langchain-cohere/src/rerank.ts [hunk 2]
```diff
@@ -60,6 +60,9 @@ export class CohereRerank extends BaseDocumentCompressor {
     documents: Array<DocumentInterface>,
     query: string
   ): Promise<Array<DocumentInterface>> {
+    if (documents == null || documents.length == 0) {
```
Comment (jacoblee93) [inline libs/langchain-cohere/src/rerank.ts:63]: Use tripel equals

File: langchain/src/chains/combine_documents/base.ts (hunk 1 above)
Comment (ahm750) [reply langchain/src/chains/combine_documents/base.ts]: Triple equals added

File: libs/langchain-cohere/src/rerank.ts (hunk 2 above)
Comment (ahm750) [reply libs/langchain-cohere/src/rerank.ts]: Triple equals added

**Comment by ahm750** [comment]
@jacoblee93 applied the changes you requested.

**Comment by ahm750** [comment]
Can you ensure this fix is included in the next release? We're unable to use the Cohere reranker due to this bug.

**Comment by jacoblee93** [comment]
Hey apologies for the delay! Will aim to get it out tonight
