### PR TITLE
core[patch]: Remove signal event listener when completed

### LINKED ISSUE #6461: Node warning after langchain upgrade to 0.2.13 Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. MaxListeners is 10. Use events.setMaxListeners() to increase limit
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Getting error when running langchain

### Error Message and Stack Trace (if applicable)

(node:62032) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. MaxListeners is 10. Use events.setMaxListeners() to increase limit
    at [kNewListener] (node:internal/event_target:566:17)
    at [kNewListener] (node:internal/abort_controller:240:24)
    at EventTarget.addEventListener (node:internal/event_target:679:23)
    at /home/langchainnode_modules/@langchain/core/dist/utils/signal.cjs:18:20
    at new Promise (<anonymous>)
    at raceWithSignal (/home/langchainnode_modules/@langchain/core/dist/utils/signal.cjs:17:9)
    at RunnableMap._transform (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:1397:79)
    at _transform.next (<anonymous>)
    at RunnableMap._transformStreamWithConfig (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:307:30)
    at _transformStreamWithConfig.next (<anonymous>)
    at PromptTemplate.transform (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:390:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatOpenAI.transform (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:390:26)
    at async wrapInputForTracing (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:274:30)
    at async pipeGeneratorWithSetup (/home/langchainnode_modules/@langchain/core/dist/utils/stream.cjs:260:19)
    at async StringOutputParser._transformStreamWithConfig (/home/langchainnode_modules/@langchain/core/dist/runnables/base.cjs:295:26)

### Description

Getting the warning in node after upgrading langchain to latest versions. 

"@langchain/community": "0.2.25",
"@langchain/openai": "0.2.6",
"langchain": "0.2.13",

### System Info

"@langchain/community": "0.2.25",
"@langchain/openai": "0.2.6",
"langchain": "0.2.13",

### PR DESCRIPTION
**Pull request by jacoblee93**
Partially fixes #6461, though if more than 10 runnables in a chain run in parallel this warning will likely resurface.

CC @nfcampos

### CODE REVIEW

File: langchain-core/src/utils/signal.ts [hunk 1]
```diff
@@ -14,13 +15,14 @@ export async function raceWithSignal<T>(
       }
     }),
     new Promise<never>((_, reject) => {
-      signal.addEventListener("abort", () => {
+      listener = () => {
         reject(new Error("Aborted"));
```
Comment (nfcampos) [inline langchain-core/src/utils/signal.ts:19]: I think the remove call should be inside the listener?

Comment (jacoblee93) [reply langchain-core/src/utils/signal.ts:19]: Could add it in both places but it should be removed once the promise resolves too?

What's the benefit to putting it within the listener vs. in `finally`?
