### PR TITLE
fix(langchain-aws): add support for Amazon Nova embedding models

### LINKED ISSUE #9694: BedrockEmbeddings with Amazon Nova Multimodal Embeddings v1 returns ValidationException "Malformed input request: required key [messages] not found"
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use the LangChain Forum (https://forum.langchain.com/).
- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Creating this ticket to fix the LangchainJS the way the Python version was fixed [here](https://github.com/langchain-ai/langchain-aws/issues/744).

### Error Message and Stack Trace (if applicable)

We get the ValidationException "Malformed input request: required key [messages] not found"

### Description

Creating this ticket to fix the LangchainJS the way the Python version was fixed [here](https://github.com/langchain-ai/langchain-aws/issues/744).

The new Nova embedding model needs to be wired up [here](https://github.com/langchain-ai/langchainjs/blob/main/libs/providers/langchain-aws/src/embeddings.ts)

### System Info

MacOS
Node v20.19.4

### PR DESCRIPTION
**Pull request by christian-bromann**
This PR adds support for Amazon Nova embedding models (e.g., `amazon.nova-embed-text-v1`) in the `BedrockEmbeddings` class. Nova models require a different request payload format than the existing Titan models.

fixes #9694

### Problem

When using Nova embedding models with `BedrockEmbeddings`, users encounter the following error:

```
ValidationException: Malformed input request: required key [messages] not found
```

This occurs because Nova models expect a `messages` array format while the existing implementation only supports the `inputText` format used by Titan models.

### Solution

- Added detection for Nova embedding models via `isNovaEmbeddingModel()` helper function
- Updated `_embedText()` to dynamically select the correct request format:
  - **Nova models**: `{ messages: [{ role: "user", content: [{ text: "..." }] }] }`
  - **Titan models**: `{ inputText: "..." }`

### Related

- Mirrors the fix applied to the Python version: https://github.com/langchain-ai/langchain-aws/issues/744

### CODE REVIEW

File: libs/providers/langchain-aws/src/embeddings.ts [hunk 1]
```diff
@@ -6,6 +6,16 @@ import {
...
 import { CredentialType } from "./types.js";
 
+/**
+ * Checks if the given model is an Amazon Nova embedding model.
+ * Nova models require a different request format using `messages` instead of `inputText`.
+ * @param model - The model ID string
+ * @returns true if the model is a Nova embedding model
+ */
+function isNovaEmbeddingModel(model: string): boolean {
+  return model.toLowerCase().includes("nova-embed");
```
Comment (kamilcglr) [inline libs/providers/langchain-aws/src/embeddings.ts:16]: Hello, it seems this doesn’t work with the Nova 2 embedding model `amazon.nova-2-multimodal-embeddings-v1:0`.

If I’m understanding correctly, this model ID wouldn’t match the current TypeScript helper, which checks specifically for `"nova-embed"`:

```ts
function isNovaEmbeddingModel(model: string): boolean {
  return model.toLowerCase().includes("nova-embed");
}
```

In the Python implementation, the check is done more generically on `"nova"` and `"embed"` in the model ID:

```python
self._inferred_provider == "amazon" \
    and "nova" in self.model_id \
    and "embed" in self.model_id
```

I think a similar, more generic check here would also catch Nova 2 models, but please correct me if I’m missing something.

Comment (christian-bromann) [reply libs/providers/langchain-aws/src/embeddings.ts:16]: You are right, great catch! Would you be open to raise a PR?
