### PR TITLE
core[patch]: Emit stream log chunks without awaiting for the first stream chunk

### LINKED ISSUE #4230: Streaming tokens does not work
The documentation on how to do streaming is here https://js.langchain.com/docs/modules/agents/how_to/streaming

If I follow this, streaming still does not work. I've created an example repo https://github.com/rednebmas/langchain-streaming-bug

### PR DESCRIPTION
**Pull request by jacoblee93**
Fixes #4230

### CODE REVIEW

File: langchain/src/document.ts [hunk 1]
```diff
@@ -1,9 +1 @@
-import { logVersion010MigrationWarning } from "./util/entrypoint_deprecation.js";
```
Comment (bracesproul) [inline langchain/src/document.ts:1]: Why drop this?

Comment (jacoblee93) [reply langchain/src/document.ts:1]: Was logging things when importing from hub due to the `load` call.
