### PR TITLE
fixes filename / base64 conversions in openai completions converters (#9512)

### LINKED ISSUE #9512: ContentBlock.Multimodal.File not working properly on OpenAI Chat Completions API
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use the LangChain Forum (https://forum.langchain.com/).
- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

With the following code you will get `BadRequestError: 400 Missing required parameter: 'messages[0].content[1].file.file_id'.`

```
const model = new ChatOpenAI({model:"gpt-4o-mini", temperature: 0});

const filename = "sample.pdf";
const pdfData = fs.readFileSync(filename);
const base64String = pdfData.toString("base64");
const dataUrl = `data:application/pdf;base64,${base64String}`;

const textBlock: ContentBlock.Text = {
    type: "text",
    text: "Can you describe this file?",
}

const fileBlock: ContentBlock.Multimodal.File = {
    type: "file",
    mimeType: "application/pdf",
    metadata: { filename: "sample.pdf" },
    data: base64String,
}

message = new HumanMessage({contentBlocks: [textBlock,fileBlock]});
res = await model.invoke([message])
console.log(res.content);
```

For OpenAI (chat completions) you need to provide

```
{
    type: "file",
    file: {
        filename: "sample.pdf",
        file_data: dataUrl
    },
}
```

The `ContentBlock.Multimodal.Image` on the other hand works fine. So I would expect the same to be true for `ContentBlock.Multimodal.File`
```
const imageBlock: ContentBlock.Multimodal.Image = {
    type: "image",
    data: base64String,
    mimeType: "image/png",
}

res = await model.invoke([new HumanMessage({
    contentBlocks: [
        textBlock,
        imageBlock,
    ],
})]);
console.log(res.content);
```

### Error Message and Stack Trace (if applicable)

```
BadRequestError: 400 Missing required parameter: 'messages[0].content[1].file.file_id'.
    at Function.generate (/Users/davydewaele/Projects/Personal/langchain-tutorial/node_modules/openai/src/core/error.ts:72:14)
    at OpenAI.makeStatusError (/Users/davydewaele/Projects/Personal/langchain-tutorial/node_modules/openai/src/client.ts:478:28)
    at OpenAI.makeRequest (/Users/davydewaele/Projects/Personal/langchain-tutorial/node_modules/openai/src/client.ts:728:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async <anonymous> (/Users/davydewaele/Projects/Personal/langchain-tutorial/node_modules/@langchain/openai/src/chat_models/completions.ts:444:18)
    at async pRetry (file:///Users/davydewaele/Projects/Personal/langchain-tutorial/node_modules/p-retry/index.js:195:19)
    at async run (/Users/davydewaele/Projects/Personal/langchain-tutorial/node_modules/p-queue/dist/index.js:163:29) {
  status: 400,
  headers: Headers {},
  requestID: 'req_33e58db7ec4b41edaa825adc455723e5',
  error: {
    message: "Missing required parameter: 'messages[0].content[1].file.file_id'.",
    type: 'invalid_request_error',
    param: 'messages[0].content[1].file.file_id',
    code: 'missing_required_parameter'
  },
  code: 'missing_required_parameter',
  param: 'messages[0].content[1].file.file_id',
  type: 'invalid_request_error'
}


Node.js v20.17.0
```

### Description

Using ContentBlock.Multimodal.File should work out of the box with OpenAI Chat Completions API to process a PDF file.

instead if generates the following (bad) payload 

- filename is missing
- file_data is converted to a base64 string while openai expects a data url

```
{
  "model" : "gpt-4o-mini",
  "temperature" : 0,
  "stream" : false,
  "messages" : [ {
    "role" : "user",
    "content" : [ {
      "type" : "file",
      "file" : {
        "file_data" : "JVBERi0xLjQKJcOkw....=="
      }
    }, {
      "type" : "text",
      "text" : "Can you describe this PDF file?"
    } ]
  } ]
}
```

It should generate something like 

```
{
  "model" : "gpt-4o-mini",
  "temperature" : 0,
  "stream" : false,
  "messages" : [ {
    "role" : "user",
    "content" : [ {
      "type" : "file",
      "file" : {
        "filename" : "sample.pdf",
        "file_data" : "data:application/pdf;base64,JVBERi0xLjQKJcOkw....=="
      }
    }, {
      "type" : "text",
      "text" : "Can you describe this PDF file?"
    } ]
  } ]
}
```

References : 

- https://platform.openai.com/docs/guides/pdf-files?api-mode=chat (mentions that filename is required)
- https://platform.openai.com/docs/guides/images-vision?api-mode=chat&format=url (for images no filename is required)

### System Info

```
pnpm info langchain
langchain@1.1.1 | MIT | deps: 5 | versions: 348

node -v
v20.17.0

pnpm --version
9.12.1
```

### PR DESCRIPTION
**Pull request by ddewaele**
Fixes #9512

Handles 2 issues with [OpenAI Completions API file uploads](https://platform.openai.com/docs/guides/pdf-files?api-mode=chat)

- filename is required
- base64 payload should always be in a dataurl format

the filename requirement was obscured by an OpenAI response error (`Missing required parameter: 'messages[0].content[1].file.file_id'`) while it can be validated upfront 
the `ContentBlock.Multimodal.File` data field (base64 string) needs to be converted to a base64 data url

Handles 1 issue with the [OpenAI Responses API file uploads](https://platform.openai.com/docs/guides/pdf-files?api-mode=responses)

- filename is required

the filename requirement was obscured by an OpenAI response error while it can be validated upfront

### CODE REVIEW

File: libs/providers/langchain-openai/src/converters/responses.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ import type {
 import { ResponseInputMessageContentList } from "openai/resources/responses/responses.js";
 import { ChatOpenAIReasoningSummary } from "../types.js";
 import { isCustomToolCall, parseCustomToolCall } from "../utils/tools.js";
-import { iife, isReasoningModel, messageToOpenAIRole } from "../utils/misc.js";
+import {getRequiredFilenameFromMetadata, iife, isReasoningModel, messageToOpenAIRole} from "../utils/misc.js";
```
Comment (christian-bromann) [inline libs/providers/langchain-openai/src/converters/responses.ts]:
```suggestion
import { getRequiredFilenameFromMetadata, iife, isReasoningModel, messageToOpenAIRole} from "../utils/misc.js";
```

File: libs/providers/langchain-openai/src/utils/misc.ts [hunk 2]
```diff
@@ -25,6 +25,19 @@ export function extractGenericMessageCustomRole(message: ChatMessage) {
...
+        block.metadata?.name ??
+        block.metadata?.title) as string;
+
+    if (!filename) {
+        throw new Error("a filename or name or title is needed via meta-data for OpenAI when working with multimodal blocks");
+    }
+
+    return filename;
+
+}
```
Comment (christian-bromann) [inline libs/providers/langchain-openai/src/utils/misc.ts]:
```suggestion
export function getRequiredFilenameFromMetadata(
  block:
    | ContentBlock.Multimodal.File
    | ContentBlock.Multimodal.Video
    | Data.StandardFileBlock
): string {
  const filename = (block.metadata?.filename ??
    block.metadata?.name ??
    block.metadata?.title) as string;

  if (!filename) {
    throw new Error(
      "a filename or name or title is needed via meta-data for OpenAI when working with multimodal blocks"
    );
  }

  return filename;
}
```

**Review by christian-bromann — COMMENTED** [review]
Thanks for raising this PR! Can we fix the formatting?

**Comment by ddewaele** [comment]
> Thanks for raising this PR! Can we fix the formatting?

Sure ... I ran the `pnpm run format` (apologies, assumed it was done during the build)

Still had one doubt about the new `contentBlocks` introduced in v1. Left message on the forum so others might also benefit from it.

https://forum.langchain.com/t/langchain-messages-content-vs-contentblocks-properties/2377

I assume these can be used  

- on the input (when contentBlock types are provided and sent to the LLM where they are serialized to model compatible format)
- on the output (when the model returns (multimodal) content and these need to be deserialized into the common contentBlock types

This PR now forced the filename to be present on the input (otherwise the openAI calls will fail anyway). Not sure how this works on the output. If you want I can take a look at that or if you have a case in mind you would like to see tested feel free to let me know
