### PR TITLE
fix(google-common): don't set includeThoughts

### LINKED ISSUE #8119: Cannot set the include thoughts parameter for Google Gemini
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [ ] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

In gemini.ts, `includeThoughts` parameter for when the reasoning is enabled is hardcoded. We should expose that parameter in `GoogleAIModelRequestParams`.

Gemini.ts -> formatGenerationConfig function
```typescript
  // Add thinking configuration if explicitly set
  if (typeof parameters.maxReasoningTokens !== "undefined") {
    ret.thinkingConfig = {
      thinkingBudget: parameters.maxReasoningTokens,
      includeThoughts: true,
    };
  }
```
Also, if maxReasoningTokens is explicitly set to 0, this code still sets `includeThoughts` to be true, which causes the following error: `Unable to submit request because Thinking_config.include_thoughts is only enabled when thinking is enabled..`

### Error Message and Stack Trace (if applicable)

_No response_

### Description

I'd like to be able to set `includeThoughts` parameter for gemini reasoning models. Right now, it's hardcoded to be 'true'.

### System Info

langchain@0.3.24 | MIT | deps: 12 | versions: 319
MacOS
Node version: v23.7.0

### PR DESCRIPTION
**Pull request by iltenahmet**
Fixes #8119.

- Enables includeThoughts parameter to be set by the user.
- Adds thinking configuration if maxReasoningTokens is not undefined AND not zero. (previously we weren't checking for zero)
- Adds tests

### CODE REVIEW

**Comment by afirstenberg** [comment]
I'm staring at the code, and I'm not sure why I included `includeThoughts` at all, since it is currently ignored by Gemini. (And I'm irritated at myself that I left it in.)

My suggestion would be:
* Do not offer this as another parameter
* Remove the line `includeThoughts:true` completely.

**Comment by iltenahmet** [comment]
@afirstenberg Thanks for the reply, I think they recently stopped ignoring it for vertex api, because suddenly we started getting reasoning steps in the response.

**Comment by afirstenberg** [comment]
> @afirstenberg Thanks for the reply, I think they recently stopped ignoring it for vertex api, because suddenly we started getting reasoning steps in the response.

Yeah, I'm just finding out details as well. There are also some other details that are changing that I'll try to put in an issue to track soon.

I might suggest we make the fix that sets `includeThoughts` to **false** by default as a rapid fix while we work out the right strategy to get the thinking tokens represented. 
Does that sound reasonable to you, @iltenahmet? (cc: @benjamincburns)

**Comment by iltenahmet** [comment]
> Yeah, I'm just finding out details as well. There are also some other details that are changing that I'll try to put in an issue to track soon.

Sounds good to me will update this pr.

**Review by benjamincburns — APPROVED** [review]

**Comment by benjamincburns** [comment]
Thanks for the quick turnaround on this @iltenahmet! I'll get this released ASAP (likely within a few hours, as I have some meetings coming up)

File: libs/langchain-google-common/src/utils/gemini.ts [hunk 1]
```diff
@@ -1367,10 +1367,14 @@ export function getGeminiAPI(config?: GeminiAPIConfig): GoogleAIAPI {
     }
 
     // Add thinking configuration if explicitly set
-    if (typeof parameters.maxReasoningTokens !== "undefined") {
+    if (
+      typeof parameters.maxReasoningTokens !== "undefined" &&
+      parameters.maxReasoningTokens !== 0
+    ) {
       ret.thinkingConfig = {
         thinkingBudget: parameters.maxReasoningTokens,
```
Comment (LoganDickey) [inline libs/langchain-google-common/src/utils/gemini.ts:1375]: Forgive me if this is the wrong place to comment (or outright incorrect) - but per https://ai.google.dev/gemini-api/docs/thinking I believe that thinking is set to on by default, and must be set to 0 explicitly to disable.

Is there a way to disable thinking with these models that I'm missing?

> "Thinking is on by default in both the API and AI Studio because the 2.5 series models have the ability to automatically decide when and how much to think based on the prompt"

Comment (afirstenberg) [reply libs/langchain-google-common/src/utils/gemini.ts:1375]: ... bah.
We introduced a bug and we and the tests didn't catch it.
See #8145 

You **should** be able to set `maxReasoningTokens` to 0 to turn it off.
