### PR TITLE
fix(openai): declarative defaultOptions

### LINKED ISSUE #8586: langchain/openai bindtools / withConfig behavior has changed / is broken (?)
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use the LangChain Forum (https://forum.langchain.com/).
- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Code used : 
```
import { ChatOpenAI } from "@langchain/openai";
import { HumanMessage } from "@langchain/core/messages";
import { z } from "zod";
import {tool} from "@langchain/core/tools";
import dotenv from 'dotenv'

dotenv.config()

const llm = new ChatOpenAI({
    model: "gpt-4o-mini",
    temperature: 0
});

const addTool = tool(
    async ({ a, b }) => {
        console.log("addTool is being called with a: ", a, " and b: ", b, "");
        return a + b;
    },
    {
        name: "add",
        schema: z.object({
            a: z.number(),
            b: z.number(),
        }),
        description: "Adds a and b.",
    }
);

const multiplyTool = tool(
    async ({ a, b }) => {
        return a * b;
    },
    {
        name: "multiply",
        schema: z.object({
            a: z.number(),
            b: z.number(),
        }),
        description: "Multiplies a and b.",
    }
);

const llmWithAddTool = llm.bindTools([addTool]);
const llmWithMultiplyTool = llm.bindTools([multiplyTool]);

const messages = [new HumanMessage("What kind of tools do you have?")];

const aiMessage = await llm.invoke(messages);
const aiMessageAdd = await llmWithAddTool.invoke(messages);
const aiMessageMultiply = await llmWithMultiplyTool.invoke(messages);

console.log("llmWithoutTools = ", aiMessage.content);
console.log("llmWithAddTool = ", aiMessageAdd.content);
console.log("llmWithMultiply = ", aiMessageMultiply.content);
```

### Error Message and Stack Trace (if applicable)

Expected behavior of the following code  (with the older `langchain/openai 0.5.18`) : 

(an llm without tools will typically hallucinate tools ... notice how none of the tools are actually tools")

```
llmWithoutTools =  I have access to a variety of math tools, including:

1. **Symbolic Math**: This tool allows for algebraic manipulation, solving equations, and working with expressions symbolically.
2. **Numerical Computation**: This tool is used for performing numerical calculations, including solving equations numerically and evaluating functions.
3. **Graphing**: This tool enables the visualization of functions and data through graphs.
4. **Statistics**: This tool provides capabilities for statistical analysis, including descriptive statistics, probability distributions, and hypothesis testing.

If you have a specific math problem or task in mind, feel free to ask!
llmWithAddTool =  I have access to the following math tool:

- `functions.add`: This tool adds two numbers together. 

If you need to perform an addition, just let me know the numbers!
llmWithMultiply =  I have access to the following math tool:

- **functions.multiply**: This tool multiplies two numbers, a and b.

```

Current behavior (with `langchain/openai 0.6.3`) : 

```
llmWithoutTools =  I have access to the following math tool:

- `functions.multiply`: This tool multiplies two numbers, `a` and `b`.
llmWithAddTool =  I have access to the following math tool:

- **functions.multiply**: This tool multiplies two numbers, a and b.
llmWithMultiply =  I have access to the following math tool:

- **functions.multiply**: This tool multiplies two numbers, a and b.

```

### Description

With the introduction of `withConfig` / `defaultOptions` , the way that llm binding tools work has changed.

This (among other things) results in upstream projects like langgraphjs supervisor to stop working
(cfr https://github.com/langchain-ai/langgraphjs/issues/1460)

`defaultOptions` are now stored as state n the underlying llm, making it no longer possible to have different agents using different tools. 

### System Info

```
openai-0.5@1.0.0 /Users/davydewaele/Projects/AgenticAI/langchain-openai-bug/openai-0.5
├── @langchain/openai@0.6.3
└── dotenv@17.2.1
```

### PR DESCRIPTION
**Pull request by hntrl**
fixes #8586

### CODE REVIEW

File: libs/langchain-openai/src/chat_models.ts [hunk 1]
```diff
@@ -3404,7 +3404,8 @@ export class ChatOpenAI<
   override withConfig(
     config: Partial<CallOptions>
   ): Runnable<BaseLanguageModelInput, AIMessageChunk, CallOptions> {
-    this.defaultOptions = { ...this.defaultOptions, ...config };
-    return this;
+    const newModel = new ChatOpenAI<CallOptions>(this.fields);
+    newModel.defaultOptions = { ...this.defaultOptions, ...config };
+    return newModel;
```
Comment (hntrl) [inline libs/langchain-openai/src/chat_models.ts:3409]: 🙈
