### PR TITLE
fix(langchain): default strict to true in providerStrategy for OpenAI compatibility

### LINKED ISSUE #9721: The `MY_TOOL_NAME` tool is not marked with `strict: true`. Only strict function tools can be auto-parsed
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use the LangChain Forum (https://forum.langchain.com/).
- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
    agent = createAgent({
      model: 'openai:gpt-5.2',
      systemPrompt: agentSystemPrompt,
      tools: [myTool1, myTool2, myTool3],
      responseFormat: providerStrategy(ExpectedesponseFormatSchema),
      contextSchema: ExtendedContextSchema,
    });
```

### Error Message and Stack Trace (if applicable)

This is the output from Langsmith

```
The `MY_TOOL_NAME` tool is not marked with `strict: true`. Only strict function tools can be auto-parsed

Error: The `MY_TOOL_NAME` tool is not marked with `strict: true`. Only strict function tools can be auto-parsed
    at validateInputTools (file:///Users/MY_PROJECT_PATH/node_modules/.pnpm/openai@6.15.0_zod@4.2.1/node_modules/openai/src/lib/parser.ts:306:13)
    at Completions.parse (file:///Users/MY_PROJECT_PATH/node_modules/.pnpm/openai@6.15.0_zod@4.2.1/node_modules/openai/src/resources/chat/completions/completions.ts:145:5)
    at file:///Users/MY_PROJECT_PATH/node_modules/.pnpm/@langchain+openai@1.2.0_@langchain+core@1.1.8_openai@6.15.0_zod@4.2.1__/node_modules/@langchain/openai/src/chat_models/completions.ts:441:53
    at pRetry.onFailedAttempt.error.error (file:///Users/MY_PROJECT_PATH/node_modules/.pnpm/@langchain+core@1.1.8_openai@6.15.0_zod@4.2.1_/node_modules/@langchain/core/src/utils/async_caller.ts:114:13)
    at pRetry (file:///Users/MY_PROJECT_PATH/node_modules/.pnpm/@langchain+core@1.1.8_openai@6.15.0_zod@4.2.1_/node_modules/@langchain/core/src/utils/p-retry/index.js:236:28)
    at async run (/Users/MY_PROJECT_PATH/node_modules/.pnpm/p-queue@6.6.2/node_modules/p-queue/dist/index.js:163:29)
```

### Description

I have updated langchain and all the other dependencies. Now the code is throwing this error

### System Info

```
{
    "@iarna/toml": "^2.2.5",
    "@langchain/core": "^1.1.8",
    "@langchain/google-genai": "^2.1.3",
    "@langchain/langgraph": "^1.0.7",
    "@langchain/openai": "^1.2.0",
    "@types/glob": "^9.0.0",
    "dotenv": "^17.2.3",
    "glob": "^13.0.0",=
    "langchain": "^1.2.3",
    "zod": "^4.2.1"
  }
```

### PR DESCRIPTION
**Pull request by christian-bromann**
When using `providerStrategy()` with `createAgent` and tools, OpenAI's `parse()` method requires all function tools to have `strict: true` set.

Previously, `providerStrategy()` defaulted `strict` to `false`, causing the error: "The MY_TOOL_NAME tool is not marked with `strict: true`. Only strict function tools can be auto-parsed"

This change:
- Defaults `strict` to `true` in `providerStrategy()`
- Adds `PROVIDER_STRATEGY_DEFAULT_STRICT` constant with documentation
- Adds integration test for providerStrategy with OpenAI and tools

Users who explicitly need `strict: false` can still pass it via:
`providerStrategy({ schema: MySchema, strict: false })`

Fixes #9721

### CODE REVIEW

**Comment by nadavgb** [comment]
Hey @christian-bromann,
I had the similar bug as the original issue so i tested the PR in my setup but it still failed here: `/libs/providers/langchain-openai/src/chat_models/completions.ts`.

GPT patched it as follows:
image

hopefully this can help fix my bug as well.

File: libs/langchain/src/agents/responses.ts [hunk 1]
```diff
@@ -25,6 +25,17 @@ export type ResponseFormatUndefined = {
...
+/**
+ * Default value for strict mode in providerStrategy.
+ *
+ * When using providerStrategy with json_schema response format, OpenAI's parse() method
+ * requires all function tools to have strict: true. This ensures the model's output
+ * exactly matches the provided JSON schema.
+ *
+ * @see https://platform.openai.com/docs/guides/structured-outputs
+ */
+const PROVIDER_STRATEGY_DEFAULT_STRICT = true;
```
Comment (hntrl) [inline libs/langchain/src/agents/responses.ts:37]: nit: what's the purpose of breaking this out?

Comment (christian-bromann) [reply libs/langchain/src/agents/responses.ts:37]: We are using it at 2 places , so this ensures we have the same default value for both of them.

**Comment by christian-bromann** [comment]
> i tested the PR in my setup but it still failed here: `/libs/providers/langchain-openai/src/chat_models/completions.ts`.

I wasn't able to reproduce this. With
```ts
const agent = createAgent({
  model: "openai:gpt-4o",
  systemPrompt:
    "You are a helpful assistant. Use the available tools to answer questions.",
  tools: [weatherTool],
  responseFormat: providerStrategy(ResponseSchema),
});
```
I got these logs:
```
request.response_format {
  type: 'json_schema',
  json_schema: {
    name: 'extract',
    description: undefined,
    schema: {
      type: 'object',
      properties: [Object],
      required: [Array],
      additionalProperties: false,
      '$schema': 'http://json-schema.org/draft-07/schema#'
    },
    strict: true
  }
}
request.tools [
  {
    type: 'function',
    function: {
      name: 'get_weather',
      description: 'Get the current weather for a location',
      parameters: [Object],
      strict: true
    }
  }
]
```
However setting it to:
```ts
const agent = createAgent({
  model: "openai:gpt-4o",
  systemPrompt:
    "You are a helpful assistant. Use the available tools to answer questions.",
  tools: [weatherTool],
  responseFormat: providerStrategy({
    schema: ResponseSchema,
    strict: false,
  }),
});
```
I got:
```
request.response_format {
  type: 'json_schema',
  json_schema: {
    name: 'extract',
    description: undefined,
    schema: {
      type: 'object',
      properties: [Object],
      required: [Array],
      additionalProperties: false,
      '$schema': 'http://json-schema.org/draft-07/schema#'
    },
    strict: false
  }
}
request.tools [
  {
    type: 'function',
    function: {
      name: 'get_weather',
      description: 'Get the current weather for a location',
      parameters: [Object],
      strict: false
    }
  }
]
```

> does changing strict defaults have any knock on effects for other providers?

Afaik there isn't really a strict option for tools in other provider.

**Review by hntrl — APPROVED** [review]
